### ISSUE TITLE
ERROR ON EXPORT VIDEO (CODE 1)

### ISSUE THREAD

**Issue by Kimsoer** [LeGoffMael/video_editor#1]
I have error while save to export video after i crop it ready.

The error is : 

D/flutter-ffmpeg(20703): Running FFmpeg with arguments: [-i, /data/user/0/com.example.download_demo/cache/image_picker5646093647845163297.jpg, -ss, 0:00:00.000000, -t, 0:21:15.169000, -filter:v, crop=335.38439822313285:220.61764600800285:0.0:0.0,scale=iw*0.5:ih*0.5,fps=10, -loop, 0, -c:a, copy, -crf, 0, -y, /data/user/0/com.example.download_demo/cacheimage_picker5646093647845163297.gif].
E/mobile-ffmpeg(20703): Unrecognized option 'crf'.
E/mobile-ffmpeg(20703): Error splitting the argument list: 
E/mobile-ffmpeg(20703): Option not found
D/flutter-ffmpeg(20703): FFmpeg exited with rc: 1
I/flutter (20703): ERROR ON EXPORT VIDEO (CODE 1)

**Comment by seel-channel** [comment]
Solved error on **1.0.0+1**

**Comment by Kimsoer** [comment]
but i test still error

**Comment by seel-channel** [comment]
Are you using a phsycal device or an emulator?

**Comment by Kimsoer** [comment]
physical device, not emulator

**Comment by seel-channel** [comment]
I removed the **-crf 0** error on the release 1.0.1+1. Can you send me the new error?

**Comment by seel-channel** [comment]
Hello! I think I solved that problem on release 1.0.2. Can you tell me if it worked?

**Comment by AyazKhalid70** [comment]
i am also getting this error on IOS video_editor: ^1.0.2

**Comment by AyazKhalid70** [comment]
> Hello! I think I solved that problem on release 1.0.2. Can you tell me if it worked?

not working on ios, on android its working fine.. please check

**Comment by s9978** [comment]
Hello, i am facing same issue in IOS and Android both.

sometimes, i am getting this in logs: IT WORKS FINE
Running FFmpeg with arguments: [-i, /data/user/0/com.medbound.app/cache/file_picker/VID-20210211-WA0009.mp4, -crf, 17, -filter:v, crop=360.0:360.0:0.0:0.0,scale=iw*1.0:ih*1.0, -preset, medium, -ss, 0:00:00.000000, -to, 0:00:03.073017, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID-20210211-WA0009.mp4].

sometimes, i am getting this in logs: WHICH IS NOT WORKING
Running FFmpeg with arguments: [-i, /storage/emulated/0/WhatsApp/Media/WhatsApp, Video/VID-20210211-WA0009.mp4, -crf, 17, -filter:v, crop=360.0:360.0:0.0:0.0,scale=iw*1.0:ih*1.0, -preset, medium, -ss, 0:00:00.000000, -to, 0:00:01.862144, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID-20210211-WA0009.mp4]. 

I think, there is some issue related to path. as you can see the difference in the second params of the array.

**Comment by AyazKhalid70** [comment]
> Hello, i am facing same issue in IOS and Android both.
> 
> sometimes, i am getting this in logs: IT WORKS FINE
> Running FFmpeg with arguments: [-i, /data/user/0/com.medbound.app/cache/file_picker/VID-20210211-WA0009.mp4, -crf, 17, -filter:v, crop=360.0:360.0:0.0:0.0,scale=iw_1.0:ih_1.0, -preset, medium, -ss, 0:00:00.000000, -to, 0:00:03.073017, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID-20210211-WA0009.mp4].
> 
> sometimes, i am getting this in logs: WHICH IS NOT WORKING
> Running FFmpeg with arguments: [-i, /storage/emulated/0/WhatsApp/Media/WhatsApp, Video/VID-20210211-WA0009.mp4, -crf, 17, -filter:v, crop=360.0:360.0:0.0:0.0,scale=iw_1.0:ih_1.0, -preset, medium, -ss, 0:00:00.000000, -to, 0:00:01.862144, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID-20210211-WA0009.mp4].
> 
> I think, there is some issue related to path. as you can see the difference in the second params of the array.

seems like your input path is not correct

**Comment by seel-channel** [comment]
I see the same issue in several devices. The export function works on some device but on another devices don't work.

I don't know where is the problem. I think is FFMPEG problem because the instructions are correct but the export don't works

**Comment by s9978** [comment]
> > Hello, i am facing same issue in IOS and Android both.
> > sometimes, i am getting this in logs: IT WORKS FINE
> > Running FFmpeg with arguments: [-i, /data/user/0/com.medbound.app/cache/file_picker/VID-20210211-WA0009.mp4, -crf, 17, -filter:v, crop=360.0:360.0:0.0:0.0,scale=iw_1.0:ih_1.0, -preset, medium, -ss, 0:00:00.000000, -to, 0:00:03.073017, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID-20210211-WA0009.mp4].
> > sometimes, i am getting this in logs: WHICH IS NOT WORKING
> > Running FFmpeg with arguments: [-i, /storage/emulated/0/WhatsApp/Media/WhatsApp, Video/VID-20210211-WA0009.mp4, -crf, 17, -filter:v, crop=360.0:360.0:0.0:0.0,scale=iw_1.0:ih_1.0, -preset, medium, -ss, 0:00:00.000000, -to, 0:00:01.862144, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID-20210211-WA0009.mp4].
> > I think, there is some issue related to path. as you can see the difference in the second params of the array.
> 
> seems like your input path is not correct

i am not getting. what yo u said. i think there is issue with FFMPEG.

**Comment by s9978** [comment]
> I see the same issue in several devices. The export function works on some device but on another devices don't work.
> 
> I don't know where is the problem. I think is FFMPEG problem because the instructions are correct but the export don't works

so, what we are supposed to do now?

**Comment by seel-channel** [comment]
> > I see the same issue in several devices. The export function works on some device but on another devices don't work.
> > 
> > I don't know where is the problem. I think is FFMPEG problem because the instructions are correct but the
> so, what we are supposed to do now?
> 

I don't know. My laptop is broken, in some days I will get one and I'm going to fix it

**Comment by seel-channel** [comment]
I just released the 1.0.3 version. Please use it with the "min-gpl-lts" package

**Comment by s9978** [comment]
> I just released the 1.0.3 version. Please use it with the "min-gpl-lts" package

it is still not working and having same issue.

**Comment by seel-channel** [comment]
> it is still not working and having same issue.

On the example, The export function has the preset and crf arguments, please remove them.

```dart
final File file = await _controller.exportVideo(
      customInstruction: "-crf 17",
      preset: VideoExportPreset.medium,
    );
```

```dart
final File file = await _controller.exportVideo(
      preset: VideoExportPreset.none,
    );
```

Note: Are you using the "min-gpl-package"?

**Comment by s9978** [comment]
Hello, @seel-channel ,
I found the issue, when the folder name of any directory is separated by space then flutterffmpeg plugin breaks the path from the space

Like:- 
Running FFmpeg with arguments: [-i, **/storage/emulated/0/Movies/Insta, gram/VID_79881220_233852_421.mp4**, -filter:v, crop=720.0:1440.0:0.0:0.0,scale=iw*1.0:ih*1.0, -preset, medium, -ss, 0:00:01.138848, -to, 0:00:02.531838, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID_79881220_233852_421.mp4].

This should be :-
Running FFmpeg with arguments: [-i, **/storage/emulated/0/Movies/Insta gram/VID_79881220_233852_421.mp4**, -filter:v, crop=720.0:1440.0:0.0:0.0,scale=iw*1.0:ih*1.0, -preset, medium, -ss, 0:00:01.138848, -to, 0:00:02.531838, -c:a, copy, -y, /data/user/0/com.medbound.app/cacheVID_79881220_233852_421.mp4].

So, path should be contain spaces in name of directory. e.g: "WhatsApp Videos"

**Comment by seel-channel** [comment]
Great! Thanks you so much

**Comment by Usama3074** [comment]
I have tried every solution suggested above but still getting the error
ERROR ON EXPORT VIDEO (CODE 1)

**Comment by lucasvps** [comment]
Any help? Still having the error
