### ISSUE TITLE
Set crop programmatically

### ISSUE THREAD

**Issue by LeGoffMael** [LeGoffMael/video_editor#10]
First, thank you for this well-build library.

Could it be possible to define the crop of the video programmatically (without user interaction) by providing a Rect object to the CropGrid for example ?

For example, I'm looking to have all my videos cropped to a square format and I would like to do this without user interaction.

Is there anyway to implements that kind of feature ?
Thank you!

**Comment by seel-channel** [comment]
Yes, you can. You are going to use the VideoEditorController.

```dart
final controller = VideoEditorController();

//Without notifyListeners()
controller.maxCrop = Offset(0.75, 0.75);
controller.minCrop = Offset(0.25, 0.25);

//With notifyListeners()
controller.updateCrop(Offset(0.25, 0.25), Offset(0.75, 0.75));
```

**Comment by LeGoffMael** [comment]
Indeed, the crop work nicely, I hadn't noticed that the offsets had to be between 0 and 1.

```dart
_controller = VideoEditorController.file(widget.file, trimStyle: trimStyle, cropStyle: cropStyle);

_controller.updateCrop(Offset(0.0, 0.1), Offset(1.0, 0.9));

_controller.initialize().then((_) {
  setState(() {});
});
```

But it looks like that the `Rect` size is not updated either in the `CropGrid` or in the `TrimSlider`. So the painted area is shown anyway. Like in below example the painted area is in blue.

![IMG_2338](https://user-images.githubusercontent.com/22376981/108966264-4dbe1280-76c1-11eb-8ea9-37852137f558.jpg)

Is there a way to hide those rectangles without having to set the same background color to the rectangles and the app ?
Thank you again!

**Comment by seel-channel** [comment]
The .updateCrop() has a notifyListeners(). The nofitfy is like a setState() then the widget needs to be mounted.

Exactly, the minCrop and maxCrop need to be in range between 0 and 1.0, because the view size always change. For example, the TrimSlider thumbnails view size don't the same on ScreenCrop view size also the Original Video has a other size. 

```dart
//initState's using notifyListeners()
@override
void initState() {
    _controller = VideoEditorController.file(widget.file);
    _controller.initialize().then((_) {
      _controller.updateCrop(Offset(0.0, 0.1), Offset(1.0, 0.9));
      setState(() {});
    });
  }
});

//initState is not using notifyListeners()
@override
void initState() {
  _controller = VideoEditorController.file(widget.file);
  _controller.minCrop = Offset(0.0, 0.1);
  _controller.maxCrop = Offset(1.0, 0.9);
  _controller.initialize().then((_) => setState(() {}));
}
```

**Comment by shamnex** [comment]
Hello @seel-channel  , excellent work and it has absolutely saved my life on a project I'm working on. 

I have a similar question, how do I go about making the CropGrid static with a predefined aspectRatio but enable the scale and pan gestures on the video. I'm try to achieve an effect similar to that of Instagram picker or this [imagePlugin](https://pub.dev/packages/image_crop).

**Comment by seel-channel** [comment]
> Hello @seel-channel  , excellent work and it has absolutely saved my life on a project I'm working on. 
> 
> I have a similar question, how do I go about making the CropGrid static with a predefined aspectRatio but enable the scale and pan gestures on the video. I'm try to achieve an effect similar to that of Instagram picker or this [imagePlugin](https://pub.dev/packages/image_crop). 
> 
> 

It don't has a way to set a preferredWidth or preferredHeight like aspectRatio. In the next update I will add this feature

**Comment by LeGoffMael** [comment]
> The .updateCrop() has a notifyListeners(). The nofitfy is like a setState() then the widget needs to be mounted.
> 
> Exactly, the minCrop and maxCrop need to be in range between 0 and 1.0, because the view size always change. For example, the TrimSlider thumbnails view size don't the same on ScreenCrop view size also the Original Video has a other size.
> 
> ```dart
> //initState's using notifyListeners()
> @override
> void initState() {
>     _controller = VideoEditorController.file(widget.file);
>     _controller.initialize().then((_) {
>       _controller.updateCrop(Offset(0.0, 0.1), Offset(1.0, 0.9));
>       setState(() {});
>     });
>   }
> });
> 
> //initState is not using notifyListeners()
> @override
> void initState() {
>   _controller = VideoEditorController.file(widget.file);
>   _controller.minCrop = Offset(0.0, 0.1);
>   _controller.maxCrop = Offset(1.0, 0.9);
>   _controller.initialize().then((_) => setState(() {}));
> }
> ```

Yes and what i meant is that the video and the thumbnails are indeed cropped correctly but the extra spaces (in blue in my example) which come from the previous video size should not be displayed.

and i can't access to
```dart
_controller.minCrop = Offset(0.0, 0.1);
_controller.maxCrop = Offset(1.0, 0.9);
```
because there is no setters for those references.

Do you think it is something that could be fix in the next update ?
Thank you again

**Comment by shamnex** [comment]
> > Hello @seel-channel  , excellent work and it has absolutely saved my life on a project I'm working on.
> > I have a similar question, how do I go about making the CropGrid static with a predefined aspectRatio but enable the scale and pan gestures on the video. I'm try to achieve an effect similar to that of Instagram picker or this [imagePlugin](https://pub.dev/packages/image_crop).
> 
> It don't has a way to set a preferredWidth or preferredHeight like aspectRatio. In the next update I will add this feature

Thanks a lot man. I look forward to the next update. Would also be nice to enable gestures on the actual video as well.

Thanks for a great plugin.

**Comment by Niko-by** [comment]
> > Hello @seel-channel  , excellent work and it has absolutely saved my life on a project I'm working on.
> > I have a similar question, how do I go about making the CropGrid static with a predefined aspectRatio but enable the scale and pan gestures on the video. I'm try to achieve an effect similar to that of Instagram picker or this [imagePlugin](https://pub.dev/packages/image_crop).
> 
> It don't has a way to set a preferredWidth or preferredHeight like aspectRatio. In the next update I will add this feature

Hi friend. Tell me, how soon is the update coming out with this feature? We really need the ability to set a preferredWidth or preferredHeight like aspectRatio like of this plugin [image_crop](https://pub.dev/packages/image_crop) This is a very cool plugin. I'm really looking forward to the update)

**Comment by seel-channel** [comment]
In 2 days

**Comment by Niko-by** [comment]
> In 2 days

Thank you 🙏. We count on you very much!

**Comment by seel-channel** [comment]
I need more time. The package crash lol

**Comment by GelidGeorge** [comment]
> I need more time. The package crash lol

____________________________________________________________________________________________________________________________________
Hey There... It's a nice package... For some reason video not exporting... Can you figure out the reason...

Maybe we can work on this together here's my WhatsApp number +919008436770

I am also looking for something just like this feature but for me, I want to allow a predefined aspect ratio depending on the video orientation...
____________________________________________________________________________________________________________________________________
I/flutter (10533): [Parsed_crop_0 @ 0x7452a8bb40] Invalid too big or non positive size for width '1586' or height '328'

________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
I/ExoPlayerImpl(10533): Init cbcf762 [ExoPlayerLib/2.13.1] [DRG_sprout, Nokia 6.1 Plus, HMD Global, 29]
I/OMXClient(10533): IOmx service obtained
D/SurfaceUtils(10533): connecting to surface 0x73f8bbf010, reason connectToSurface
I/MediaCodec(10533): [OMX.qcom.video.decoder.avc] setting surface generation to 10785797
D/SurfaceUtils(10533): disconnecting from surface 0x73f8bbf010, reason connectToSurface(reconnect)
D/SurfaceUtils(10533): connecting to surface 0x73f8bbf010, reason connectToSurface(reconnect)
I/ExtendedACodec(10533): setupVideoDecoder()
I/ExtendedACodec(10533): Decoder will be in frame by frame mode
D/SurfaceUtils(10533): set up nativeWindow 0x73f8bbf010 for 1920x1080, color 0x7fa30c06, rotation 90, usage 0x20002900
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
I/OMXClient(10533): IOmx service obtained
I/ACodec  (10533): codec does not support config priority (err -2147483648)
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
I/ACodec  (10533): codec does not support config priority (err -2147483648)
I/ACodec  (10533): codec does not support config operating rate (err -2147483648)
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
W/ExtendedACodec(10533): Failed to get extension for extradata parameter
D/SurfaceUtils(10533): set up nativeWindow 0x73f8bbf010 for 1920x1088, color 0x7fa30c06, rotation 90, usage 0x20002900
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
I/chatty  (10533): uid=10199(com.stringflix.app) CodecLooper identical 1 line
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
W/MapperHal(10533): buffer descriptor with invalid usage bits 0x2000
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:197, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:394, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:592, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:789, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:987, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:1184, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:1381, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:1579, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:1776, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:1974, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:2171, quality:25 )
D/ThumbnailPlugin(10533): buildThumbnailData( format:0, maxh:0, maxw:0, timeMs:2369, quality:25 )
I/flutter (10533): Loading flutter-ffmpeg.
I/mobile-ffmpeg(10533): Loading mobile-ffmpeg.
I/mobile-ffmpeg(10533): Loaded mobile-ffmpeg-min-gpl-arm64-v8a-4.4-lts-20200724.
D/mobile-ffmpeg(10533): Callback thread started.
I/flutter (10533): Loaded flutter-ffmpeg-android-arm64-v8a.
D/flutter-ffmpeg(10533): Getting media information for /storage/emulated/0/Android/data/_/files/Pictures/ab3be2df-12b0-4386-b16d-f27aa12545bf456822202985683662.mp4.
I/flutter (10533): {
I/flutter (10533):     
I/flutter (10533): "streams": [
I/flutter (10533):         
I/flutter (10533): {
I/flutter (10533):             
I/flutter (10533): "index": 0
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_name":
I/flutter (10533):  "h264"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_long_name":
I/flutter (10533):  "unknown"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "profile":
I/flutter (10533):  "100"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_type":
I/flutter (10533):  "video"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_time_base":
I/flutter (10533):  "106589/6390000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_tag_string":
I/flutter (10533):  "avc1"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_tag":
I/flutter (10533):  "0x31637661"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "width": 1920
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "height": 1080
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "coded_width": 1920
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "coded_height": 1088
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "has_b_frames": 0
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "sample_aspect_ratio":
I/flutter (10533):  "1:1"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "display_aspect_ratio":
I/flutter (10533):  "16:9"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "pix_fmt":
I/flutter (10533):  "yuvj420p"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "level": 40
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "color_range":
I/flutter (10533):  "pc"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "color_space":
I/flutter (10533):  "smpte170m"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "color_transfer":
I/flutter (10533):  "smpte170m"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "color_primaries":
I/flutter (10533):  "smpte170m"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "chroma_location":
I/flutter (10533):  "left"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "refs": 1
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "is_avc":
I/flutter (10533):  "true"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "nal_length_size":
I/flutter (10533):  "4"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "r_frame_rate":
I/flutter (10533):  "30000/1001"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "avg_frame_rate":
I/flutter (10533):  "3195000/106589"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "time_base":
I/flutter (10533):  "1/90000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "start_pts": 0
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "start_time":
I/flutter (10533):  "0.000000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "duration_ts": 213178
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "duration":
I/flutter (10533):  "2.368644"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "bit_rate":
I/flutter (10533):  "19433359"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "bits_per_raw_sample":
I/flutter (10533):  "8"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "nb_frames":
I/flutter (10533):  "71"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "disposition": {
I/flutter (10533):                 
I/flutter (10533): "default": 1
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "dub": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "original": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "comment": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "lyrics": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "karaoke": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "forced": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "hearing_impaired": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "visual_impaired": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "clean_effects": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "attached_pic": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "timed_thumbnails": 0
I/flutter (10533): 
I/flutter (10533):             
I/flutter (10533): }
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "tags": {
I/flutter (10533):                 
I/flutter (10533): "rotate":
I/flutter (10533):  "90"
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "creation_time":
I/flutter (10533):  "2021-03-12T08:19:36.000000Z"
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "language":
I/flutter (10533):  "eng"
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "handler_name":
I/flutter (10533):  "VideoHandle"
I/flutter (10533): 
I/flutter (10533):             
I/flutter (10533): }
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "side_data_list": [
I/flutter (10533):                 
I/flutter (10533): {
I/flutter (10533):                     
I/flutter (10533): "side_data_type":
I/flutter (10533):  "Display Matrix"
I/flutter (10533): ,
I/flutter (10533):                     
I/flutter (10533): "displaymatrix":
I/flutter (10533):  "\n00000000:            0       65536           0\n00000001:       -65536           0           0\n00000002:            0           0  1073741824\n"
I/flutter (10533): ,
I/flutter (10533):                     
I/flutter (10533): "rotation": -90
I/flutter (10533): 
I/flutter (10533):                 
I/flutter (10533): }
I/flutter (10533): 
I/flutter (10533):             
I/flutter (10533): ]
I/flutter (10533): 
I/flutter (10533):         
I/flutter (10533): }
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): {
I/flutter (10533):             
I/flutter (10533): "index": 1
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_name":
I/flutter (10533):  "aac"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_long_name":
I/flutter (10533):  "unknown"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "profile":
I/flutter (10533):  "1"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_type":
I/flutter (10533):  "audio"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_time_base":
I/flutter (10533):  "1/48000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_tag_string":
I/flutter (10533):  "mp4a"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "codec_tag":
I/flutter (10533):  "0x6134706d"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "sample_fmt":
I/flutter (10533):  "fltp"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "sample_rate":
I/flutter (10533):  "48000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "channels": 2
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "channel_layout":
I/flutter (10533):  "stereo"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "bits_per_sample": 0
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "r_frame_rate":
I/flutter (10533):  "0/0"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "avg_frame_rate":
I/flutter (10533):  "0/0"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "time_base":
I/flutter (10533):  "1/48000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "start_pts": 0
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "start_time":
I/flutter (10533):  "0.000000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "duration_ts": 112041
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "duration":
I/flutter (10533):  "2.334188"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "bit_rate":
I/flutter (10533):  "94758"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "max_bit_rate":
I/flutter (10533):  "96000"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "nb_frames":
I/flutter (10533):  "108"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "disposition": {
I/flutter (10533):                 
I/flutter (10533): "default": 1
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "dub": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "original": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "comment": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "lyrics": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "karaoke": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "forced": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "hearing_impaired": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "visual_impaired": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "clean_effects": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "attached_pic": 0
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "timed_thumbnails": 0
I/flutter (10533): 
I/flutter (10533):             
I/flutter (10533): }
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "tags": {
I/flutter (10533):                 
I/flutter (10533): "creation_time":
I/flutter (10533):  "2021-03-12T08:19:36.000000Z"
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "language":
I/flutter (10533):  "eng"
I/flutter (10533): ,
I/flutter (10533):                 
I/flutter (10533): "handler_name":
I/flutter (10533):  "SoundHandle"
I/flutter (10533): 
I/flutter (10533):             
I/flutter (10533): }
I/flutter (10533): 
I/flutter (10533):         
I/flutter (10533): }
I/flutter (10533): 
I/flutter (10533):     
I/flutter (10533): ]
I/flutter (10533): ,
I/flutter (10533):     
I/flutter (10533): "format": {
I/flutter (10533):         
I/flutter (10533): "filename":
I/flutter (10533):  "/storage/emulated/0/Android/data/_/files/Pictures/ab3be2df-12b0-4386-b16d-f27aa12545bf456822202985683662.mp4"
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "nb_streams": 2
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "nb_programs": 0
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "format_name":
I/flutter (10533):  "mov,mp4,m4a,3gp,3g2,mj2"
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "start_time":
I/flutter (10533):  "0.000000"
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "duration":
I/flutter (10533):  "2.369000"
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "size":
I/flutter (10533):  "6233928"
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "bit_rate":
I/flutter (10533):  "21051677"
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "probe_score": 100
I/flutter (10533): ,
I/flutter (10533):         
I/flutter (10533): "tags": {
I/flutter (10533):             
I/flutter (10533): "major_brand":
I/flutter (10533):  "mp42"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "minor_version":
I/flutter (10533):  "0"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "compatible_brands":
I/flutter (10533):  "isommp42"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "creation_time":
I/flutter (10533):  "2021-03-12T08:19:36.000000Z"
I/flutter (10533): ,
I/flutter (10533):             
I/flutter (10533): "com.android.version":
I/flutter (10533):  "10"
I/flutter (10533): 
I/flutter (10533):         
I/flutter (10533): }
I/flutter (10533): 
I/flutter (10533):     
I/flutter (10533): }
I/flutter (10533): 
I/flutter (10533): }
D/flutter-ffmpeg(10533): Running FFmpeg with arguments: [-i, /storage/emulated/0/Android/data/_/files/Pictures/ab3be2df-12b0-4386-b16d-f27aa12545bf456822202985683662.mp4, -crf, 17, -filter:v, crop=1587.2999237804884:327.622644563999:155.95312500000088:433.7854424453373, -preset, medium, -y, /data/user/0/_/cachevideoString.mp4].
I/flutter (10533): Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Android/data/_/files/Pictures/ab3be2df-12b0-4386-b16d-f27aa12545bf456822202985683662.mp4':
I/flutter (10533):   Metadata:
I/flutter (10533):     major_brand     : 
I/flutter (10533): mp42
I/flutter (10533): 
I/flutter (10533):     minor_version   : 
I/flutter (10533): 0
I/flutter (10533): 
I/flutter (10533):     compatible_brands: 
I/flutter (10533): isommp42
I/flutter (10533): 
I/flutter (10533):     creation_time   : 
I/flutter (10533): 2021-03-12T08:19:36.000000Z
I/flutter (10533): 
I/flutter (10533):     com.android.version: 
I/flutter (10533): 10
I/flutter (10533): 
I/flutter (10533):   Duration: 
I/flutter (10533): 00:00:02.37
I/flutter (10533): , start: 
I/flutter (10533): 0.000000
I/flutter (10533): , bitrate: 
I/flutter (10533): 21051 kb/s
I/flutter (10533): 
I/flutter (10533):     Stream #0:0
I/flutter (10533): (eng)
I/flutter (10533): : Video: h264 (avc1 / 0x31637661), yuvj420p(pc, smpte170m), 1920x1080, 19433 kb/s
I/flutter (10533): , SAR 1:1 DAR 16:9
I/flutter (10533): , 
I/flutter (10533): 29.97 fps, 
I/flutter (10533): 29.97 tbr, 
I/flutter (10533): 90k tbn, 
I/flutter (10533): 180k tbc
I/flutter (10533):  (default)
I/flutter (10533): 
I/flutter (10533):     Metadata:
I/flutter (10533):       rotate          : 
I/flutter (10533): 90
I/flutter (10533): 
I/flutter (10533):       creation_time   : 
I/flutter (10533): 2021-03-12T08:19:36.000000Z
I/flutter (10533): 
I/flutter (10533):       handler_name    : 
I/flutter (10533): VideoHandle
I/flutter (10533): 
I/flutter (10533):     Side data:
I/flutter (10533):       
I/flutter (10533): displaymatrix: rotation of -90.00 degrees
I/flutter (10533): 
I/flutter (10533):     Stream #0:1
I/flutter (10533): (eng)
I/flutter (10533): : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 94 kb/s
I/flutter (10533):  (default)
I/flutter (10533): 
I/flutter (10533):     Metadata:
I/flutter (10533):       creation_time   : 
I/flutter (10533): 2021-03-12T08:19:36.000000Z
I/flutter (10533): 
I/flutter (10533):       handler_name    : 
I/flutter (10533): SoundHandle
I/flutter (10533): 
I/flutter (10533): Stream mapping:
I/flutter (10533):   Stream #0:0 -> #0:0
I/flutter (10533):  (h264 (native) -> h264 (libx264))
I/flutter (10533): 
I/flutter (10533):   Stream #0:1 -> #0:1
I/flutter (10533):  (aac (native) -> aac (native))
I/flutter (10533): 
I/flutter (10533): Press [q] to stop, [?] for help
I/flutter (10533): [graph 0 input from stream 0:0 @ 0x7452bf6500] sws_param option is deprecated and ignored
I/flutter (10533): [Parsed_crop_0 @ 0x7452a8bb40] Invalid too big or non positive size for width '1586' or height '328'
I/flutter (10533): [Parsed_crop_0 @ 0x7452a8bb40] Failed to configure input pad on Parsed_crop_0
I/flutter (10533): Error reinitializing filters!
I/flutter (10533): Failed to inject frame into filter network: Invalid argument
I/flutter (10533): Error while processing the decoded data for stream #0:0
D/flutter-ffmpeg(10533): FFmpeg exited with rc: 1
I/flutter (10533): Conversion failed!
I/flutter (10533): ERROR ON EXPORT VIDEO (CODE 1)


Flutter Doctor -v
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.2 19C57 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/gelidgeorge/Development/flutter
    • Framework revision 9b2d32b605 (7 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/gelidgeorge/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/gelidgeorge/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.54.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Nokia 6 1 Plus (mobile) • 192.168.1.8:5555 • android-arm64 • Android 10 (API 29)
    ! Error: Kelvin’s iPhone is not connected. Xcode will continue when Kelvin’s iPhone is connected. (code -13)

! Doctor found issues in 1 category.

**Comment by seel-channel** [comment]
Yes I also have this same issue sometimes. I'll add validations for this error and I think will solve it

**Comment by GelidGeorge** [comment]
May I know the reason for this issue... though... Maybe I can fix it and send a code snippet...

**Comment by seel-channel** [comment]
> May I know the reason for this issue... though... Maybe I can fix it and send a code snippet...

Please send me your code. I would like a lot :)

**Comment by seel-channel** [comment]
The FFMPEG make me crash the app. I think is a incompatible with Flutter 2.0.1. For this problem I couldn't release the new crop features

**Comment by GelidGeorge** [comment]
what if we created a native libary based on this and expose...

**Comment by GelidGeorge** [comment]
dart code...

**Comment by seel-channel** [comment]
Sounds really funny! But I don't have any knowledge about native libraries

**Comment by Niko-by** [comment]
> The FFMPEG make me crash the app. I think is a incompatible with Flutter 2.0.1. For this problem I couldn't release the new crop features

Can't you use the old version of FFMPEG and temporarily not switch to nullsafity? So that we can take advantage of your new functions))

By the way, yesterday the flutter_ffmpeg library was updated to version 0.4.0. Maybe they fixed the mistake, what do you think? Haven't checked it yet?

**Comment by Niko-by** [comment]
> I need more time. The package crash lol

Hi friend. Do you have news for us?

**Comment by seel-channel** [comment]
Done! Check the new release
