### ISSUE TITLE
Using dependency_overrides  ffmpeg_kit_flutter_min_gpl: ^4.5.1-LTS still gives minSDKVersion error

### ISSUE THREAD

**Issue by t-k-c** [LeGoffMael/video_editor#101]
Hi,  I've been trying to use the LTS version such that i don't  have  to increase my minSdkVersion to 24 to be able to support wider devices. I could at least accept the '12.1' for iOS but I really need to support 21 and above for android. It keeps rejecting even the LTS override. Is there something I'm not doing right?

**Comment by rikun5989** [comment]
In your manifest file add 
xmlns:tools="http://schemas.android.com/tools" next to your package name
then add
`<uses-sdk tools:overrideLibrary="com.arthenica.ffmpegkit.flutter"/>`
 before application tag

**Comment by LeGoffMael** [comment]
Thank you @rikun5989 i updated the readme with your fix

**Comment by diybl** [comment]
> In your manifest file add xmlns:tools="http://schemas.android.com/tools" next to your package name then add `<uses-sdk tools:overrideLibrary="com.arthenica.ffmpegkit.flutter"/>` before application tag

* What went wrong:
Execution failed for task ':app:generateDebugBuildConfig'.
> Error while evaluating property 'namespace' of task ':app:generateDebugBuildConfig'
   > Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'namespace'.
      > Failed to calculate the value of property 'namespace'.
         > org.xml.sax.SAXParseException; systemId: file:/android/app/src/main/AndroidManifest.xml; lineNumber: 3; columnNumber: 72; ��Ԫ������ "uses-sdk" ����������� "tools:overrideLibrary" ��ǰ׺ "tools" δ�󶨡�

build error。

**Comment by diybl** [comment]
> > In your manifest file add xmlns:tools="http://schemas.android.com/tools" next to your package name then add `<uses-sdk tools:overrideLibrary="com.arthenica.ffmpegkit.flutter"/>` before application tag
> 
> * What went wrong:
>   Execution failed for task ':app:generateDebugBuildConfig'.
> 
> > Error while evaluating property 'namespace' of task ':app:generateDebugBuildConfig'
> > Failed to calculate the value of task ':app:generateDebugBuildConfig' property 'namespace'.
> > > Failed to calculate the value of property 'namespace'.
> > > org.xml.sax.SAXParseException; systemId: file:/android/app/src/main/AndroidManifest.xml; lineNumber: 3; columnNumber: 72; ��Ԫ������ "uses-sdk" ����������� "tools:overrideLibrary" ��ǰ׺ "tools" δ�󶨡�
> 
> build error。

https://stackoverflow.com/questions/27095077/how-do-i-use-toolsoverridelibrary-in-a-build-gradle-file

solved.
