### ISSUE TITLE
exportVideo is not working 

### ISSUE THREAD

**Issue by wanoghoco** [LeGoffMael/video_editor#107]
exportVideo is not working after compiling apk for android and also it doesn't work on iOS after releasing to TestFlight for iOS

**Comment by wanoghoco** [comment]
<pre>
Exception: FFmpeg process exited with state COMPLETED and return code 255.
ffmpeg version v4.5-dev-3393-g30322ebe3c Copyright (c) 2000-2021 the FFmpeg developers
  built with Android (7155654, based on r399163b1) clang version 11.0.5 (https://android.googlesource.com/toolchain/llvm-project 87f1315dfbea7c137aa2e6d362dbb457e388158d)
  configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/storage/light/projects/ffmpeg-kit/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --target-os=android --enable-neon --enable-asm --enable-inline-asm --ar=aarch64-linux-android-ar --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --ranlib=aarch64-linux-android-ranlib --strip=aarch64-linux-android-strip --nm=aarch64-linux-android-nm --extra-libs='-L/storage/light/projects/ffmpeg-kit/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --disable-autodetect --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --disable-static --enable-shared --enable-pthreads --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libx264 --enable-libxvid --enable-libx265 --enable-libvidstab --disable-sdl2 --disable-openssl --enable-zlib --enable-mediacodec --enable-gpl
  libavutil      57. 13.100 / 57. 13.100
  libavcodec     59. 15.102 / 59. 15.102
  libavformat    59. 10.100 / 59. 10.100
  libavdevice    59.  1.100 / 59.  1.100
  libavfilter     8. 21.100 /  8. 21.100
  libswscale      6.  1.102 /  6.  1.102
  libswresample   4.  0.100 /  4.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/Android/data/com.lykluk.lykluk/files/Movies/video_2022_08_28_19_53_50.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2022-08-28T18:53:53.000000Z
    com.android.version: 11
  Duration: 00:00:03.00, start: 0.000000, bitrate: 8871 kb/s
  Stream #0:0[0x1](eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 720x1568, 8849 kb/s, SAR 1:1 DAR 45:98, 52.26 fps, 90k tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2022-08-28T18:53:53.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 61 kb/s (default)
    Metadata:
      creation_time   : 2022-08-28T18:53:53.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
[h264 @ 0xb400007a1daa5690] The "sub_text_format" option is deprecated: Deprecated, does nothing
[aac @ 0xb400007a1daa5240] The "sub_text_format" option is deprecated: Deprecated, does nothing
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0xb400007a1daa3410] using SAR=1/1
[libx264 @ 0xb400007a1daa3410] using cpu capabilities: ARMv8 NEON
[libx264 @ 0xb400007a1daa3410] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 0xb400007a1daa3410] 264 - core 163 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Finishing stream 0:1 without any data written to it.
Output #0, mp4, to '/data/user/0/com.lykluk.lykluk/cache/video_2022_08_28_19_53_50_1661712835461.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.version: 11
    encoder         : Lavf59.10.100
  Stream #0:0(eng): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt470bg/bt470bg/smpte170m, progressive), 720x1568 [SAR 1:1 DAR 45:98], q=2-31, 52.26 fps, 14040k tbn (default)
    Metadata:
      creation_time   : 2022-08-28T18:53:53.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.15.102 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      creation_time   : 2022-08-28T18:53:53.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.15.102 aac
frame=   18 fps= 15 q=-1.0 Lsize=      28kB time=00:00:00.28 bitrate= 785.3kbits/s dup=2 drop=0 speed=0.231x    
video:26kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4.078315%
[libx264 @ 0xb400007a1daa3410] frame I:1     Avg QP:16.67  size: 10622
[libx264 @ 0xb400007a1daa3410] frame P:5     Avg QP:18.00  size:  2804
[libx264 @ 0xb400007a1daa3410] frame B:12    Avg QP:17.37  size:   146
[libx264 @ 0xb400007a1daa3410] consecutive B-frames:  5.6% 11.1% 16.7% 66.7%
[libx264 @ 0xb400007a1daa3410] mb I  I16..4: 65.4% 34.4%  0.2%
[libx264 @ 0xb400007a1daa3410] mb P  I16..4:  0.4%  1.0%  0.0%  P16..4: 11.9%  1.2%  2.3%  0.0%  0.0%    skip:83.3%
[libx264 @ 0xb400007a1daa3410] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  2.5%  0.0%  0.0%  direct: 0.1%  skip:97.4%  L0:49.6% L1:50.3% BI: 0.1%
[libx264 @ 0xb400007a1daa3410] 8x8 transform intra:36.7% inter:77.7%
[libx264 @ 0xb400007a1daa3410] coded y,uvDC,uvAC intra: 25.3% 22.4% 0.4% inter: 1.3% 3.1% 0.0%
[libx264 @ 0xb400007a1daa3410] i16 v,h,dc,p: 81%  2%  3% 13%
[libx264 @ 0xb400007a1daa3410] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30%  9% 31%  5%  5%  6%  5%  4%  4%
[libx264 @ 0xb400007a1daa3410] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 15% 15% 35%  7%  8%  3%  7%  7%  2%
[libx264 @ 0xb400007a1daa3410] i8c dc,h,v,p: 77%  8% 10%  5%
[libx264 @ 0xb400007a1daa3410] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0xb400007a1daa3410] ref P L0: 80.0%  7.8%  5.4%  6.8%
[libx264 @ 0xb400007a1daa3410] ref B L0: 94.6%  4.8%  0.6%
[libx264 @ 0xb400007a1daa3410] kb/s:613.06
[aac @ 0xb400007a1da9d980] Qavg: nan
Exiting normally, received signal 2.
_________#0      VideoEditorController.exportVideo.<anonymous closure> (package:video_editor/domain/bloc/controller.dart:501)
<asynchronous suspension>
</pre>

**Comment by Mamasodikov** [comment]
I had the same issue.
Wrap your export method with 

```dart
Future.delayed(Duration(seconds: 1)).then((value){

//Paste your code here

})
```

I don't know why but after 3 hours of digging I found it and worked for me!

**Comment by LeGoffMael** [comment]
The latest version 3.0.0 is out.
The exportation process is not part of the package anymore
