### ISSUE TITLE
Crop on vertical not working initially

### ISSUE THREAD

**Issue by novvia-dev** [LeGoffMael/video_editor#109]
When you have a crop aspect ratio less than 1 (i.e. 9 / 16) And upload a landscape video, the initial crop is incorrect. As soon as the crop box is selected and dragged, it updates to the correct aspect ratio, but that should not be necessary.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/84742208/191128139-956da527-c180-4aff-9014-b371dbcfd8bd.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/84742208/191128171-f7975ad4-8e3d-49ac-b331-88d10aec8dae.png">

**Comment by LeGoffMael** [comment]
In version 1.5.1 you can use `aspectRatio` param in initialize function to setup the ratio. [Check example](https://github.com/seel-channel/video_editor/blob/master/example/lib/main.dart#L114).
