### ISSUE TITLE
A RenderFlex overflowed by 99940 pixels on the bottom.

### ISSUE THREAD

**Issue by dmjtian** [LeGoffMael/video_editor#119]
When  I try select 1s video，it was error:UnsupportedError (Unsupported operation: Infinity or NaN toInt)

if you want repeat this error:

error video url: [click to dowload](https://blog-1252030657.cos.ap-guangzhou.myqcloud.com/IMG_2624.mov)

all errors:
<pre>
#175    RenderObject.layout
package:flutter/…/rendering/object.dart:2135
#176    RenderBox.layout
package:flutter/…/rendering/box.dart:2418
#177    MultiChildLayoutDelegate.layoutChild
package:flutter/…/rendering/custom_layout.dart:171
#178    _ScaffoldLayout.performLayout
package:flutter/…/material/scaffold.dart:1055
#179    MultiChildLayoutDelegate._callPerformLayout
package:flutter/…/rendering/custom_layout.dart:240
#180    RenderCustomMultiChildLayoutBox.performLayout
package:flutter/…/rendering/custom_layout.dart:410
#181    RenderObject._layoutWithoutResize
package:flutter/…/rendering/object.dart:1973
#182    PipelineOwner.flushLayout
package:flutter/…/rendering/object.dart:999
#183    RendererBinding.drawFrame
package:flutter/…/rendering/binding.dart:513
#184    WidgetsBinding.drawFrame
package:flutter/…/widgets/binding.dart:884
#185    RendererBinding._handlePersistentFrameCallback
package:flutter/…/rendering/binding.dart:378
#186    SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#187    SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1104
#188    SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#189    _invoke (dart:ui/hooks.dart:148:13)
#190    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#191    _drawFrame (dart:ui/hooks.dart:115:31)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 99940 pixels on the bottom.
</pre>

**Comment by LeGoffMael** [comment]
Thank you for the report and the video link, i am able to see the issue. I'll fix it

**Comment by LeGoffMael** [comment]
Should be fix in the latest 2.0.0

**Comment by Tpow99** [comment]
I am still receiving this error

**Comment by LeGoffMael** [comment]
> I am still receiving this error

that is probably a different issue, please open a new issue with the description on how to reproduce the error

**Comment by Tpow99** [comment]
> > I am still receiving this error
> 
> that is probably a different issue, please open a new issue with the description on how to reproduce the error

If anyone is having this issue moving forward, it is an issue that can occur with the example provided. If you attempt to call the set state from the initstate and the video controller has not completed, the package finds a NaN value and overflows. The solution is to declare the controller and initialize it prior to building the page instead.
