### ISSUE TITLE
Video Editor doesnt work with newest version of chewie ^1.0.0

### ISSUE THREAD

**Issue by eugrro** [LeGoffMael/video_editor#12]
Version fixing does not work. I think updating the packages to the latest versions should do the trick. Below is the specifics:
Because no versions of video_editor match >1.0.3+1 <2.0.0 and video_editor 1.0.3+1 depends on video_player ^1.0.1, video_editor ^1.0.3+1 requires video_player ^1.0.1.
And because chewie >=1.0.0 depends on video_player ^2.0.0, video_editor ^1.0.3+1 is incompatible with chewie >=1.0.0.
So, because app depends on both chewie ^1.0.0 and video_editor ^1.0.3+1, version solving failed.

**Comment by Steven-Chen87** [comment]
same issue here.

**Comment by seel-channel** [comment]
Done! Check the new release
