### ISSUE TITLE
Weird zoom in version 1.5.2

### ISSUE THREAD

**Issue by Hash1mot0** [LeGoffMael/video_editor#120]
I'm having a weir zoom in the thumbnails and in the timeline slider after the 1.5.2 update.
This behavior does not apear in 1.5.0.

What could be happening?

1.5.0:
![01 on 1 5 0](https://user-images.githubusercontent.com/118370711/202211901-2b41b35d-7251-4bc2-87ac-aa54968f5256.png)

1.5.2:
![01 on 1 5 2](https://user-images.githubusercontent.com/118370711/202211908-cb884df4-3397-4556-b409-1d15799335c1.png)

1.5.0:
![02 on 1 5 0](https://user-images.githubusercontent.com/118370711/202211913-134434de-083a-4cf6-baa8-973bc4534af4.png)

1.5.2:
![02 on 1 5 2](https://user-images.githubusercontent.com/118370711/202211917-96751cb1-6185-4156-9ccf-8bc008cdc163.png)

**Comment by LeGoffMael** [comment]
I am aware that they are some issue with the thumbnails scale, the next update (ETA next week) should fix those

**Comment by LeGoffMael** [comment]
Should be fix in the latest 2.0.0

**Comment by Hash1mot0** [comment]
Bug fully fixed! Thanks!!!
