### ISSUE TITLE
Fatal errors: cacheMinCrop and updateCrop

### ISSUE THREAD

**Issue by Niko-by** [LeGoffMael/video_editor#13]
The last commit contains an error while compiling the application.

`_controller.cacheMinCrop = Offset(
                      ^^^^^^^^^^^^
    ../../../Documents/flutter/.pub-cache/git/video_editor-1399d23c47f24329a2d4a0c23510943129e548f2/lib/ui/widgets/crop/crop_grid.dart:206:19: Error: The setter 'cacheMaxCrop' isn't defined for the class 'VideoEditorController'.
     - 'VideoEditorController' is from 'package:video_editor/domain/bloc/controller.dart' ('../../../Documents/flutter/.pub-cache/git/video_editor-1399d23c47f24329a2d4a0c23510943129e548f2/lib/domain/bloc/controller.dart').
    Try correcting the name to the name of an existing setter, or defining a setter or field named 'cacheMaxCrop'.
          _controller.cacheMaxCrop = Offset(
                      ^^^^^^^^^^^^
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description`

Also an error in the example. Controller.updateCrop () method not found

**Comment by seel-channel** [comment]
JAJAJA LOL. I developing the next update and it isn't ready yet

**Comment by Niko-by** [comment]
> JAJAJA LOL. I developing the next update and it isn't ready yet

Very sorry. Do you have an approximate timeframe? Or is it better not to wait and look for another plugin?

**Comment by seel-channel** [comment]
Don't worry in a little days a release the new update, because I'm stock in new crop aspect ratio feature

**Comment by seel-channel** [comment]
Done! Check the new release
