### ISSUE TITLE
How to reduce video exporting time?

### ISSUE THREAD

**Issue by RzTutul** [LeGoffMael/video_editor#135]
Is there any way to reduce video exporting time? it takes much time to export a video.

**Comment by LeGoffMael** [comment]
The exportation is handled by [ffmpeg_kit](https://pub.dev/packages/ffmpeg_kit_flutter), i don't really know how to improve the exportation time

**Comment by RzTutul** [comment]
Ok. Can you add some filters?

**Comment by LeGoffMael** [comment]
I am not sure what is your question

This is the command used to export the video :
https://github.com/LeGoffMael/video_editor/blob/fb0a0686bf759b7e6b80da519461a51c76b96052/lib/domain/bloc/controller.dart#L578

You can use both `preset` and `customInstruction` to customize the exportation

**Comment by peyton-v5** [comment]
@RzTutul Did you solve it?

**Comment by jcsena** [comment]
> Is there any way to reduce video exporting time? it takes much time to export a video.

Try to use preset ultrafast and maybe if you want reduce video size you can reduce audio quality like the customInstruction .

``` dart 
  await _controller.exportVideo(
      preset: VideoExportPreset.ultrafast,
      customInstruction: '-c:a aac -b:a 64k',
 ```

**Comment by jcsena** [comment]
#140 @peyton-v5  @RzTutul I just move to custom command using the _controller variables

```dart
    final _filePath = await Utils.createTrimmedVideo(
        startValue: _controller.startTrim,
        endValue: _controller.endTrim,
        outputPath: _temporalRoute,
        videoPath: _controller.file.path,
      );
```

**Comment by LeGoffMael** [comment]
The latest version 3.0.0 is out.
It now gives you complete control of the exportation process
