### ISSUE TITLE
'Pods-Runner' target has frameworks with conflicting names

### ISSUE THREAD

**Issue by Bill550** [LeGoffMael/video_editor#137]
[!] The 'Pods-Runner' target has frameworks with conflicting names: ffmpegkit.xcframework, libavcodec.xcframework, libavdevice.xcframework, libavfilter.xcframework, libavformat.xcframework, libavutil.xcframework, libswresample.xcframework, and libswscale.xcframework.

**Comment by LeGoffMael** [comment]
seems like a pod error, have you tried to run `pod install` in ios folder ?

**Comment by craeft-io** [comment]
I get the same error but pod install doesn't solve it. The only way I get pod install to work is by removing ffmpeg_kit_flutter: ^5.1.0 from pubspec.yaml. But this is not a solution as I need this package for some other steps. 
Do you have any idea?
