### ISSUE TITLE
Video trimming doesnt work on large video, app is freeze and have to be close

### ISSUE THREAD

**Issue by ajosecueto** [LeGoffMael/video_editor#14]
I cant log this error... i'm using flutter 2 and video_editor   video_editor: ^1.0.3+1

**Comment by ajosecueto** [comment]
Happen when left part o trim get over the right and the app crash...

**Comment by ajosecueto** [comment]
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.
I/MediaCodec(12643): (0x7cc6b64000) flush
I/MediaCodec(12643): (0x7c9a245400) flush
W/Codec2Client(12643): query -- param skipped: index = 1342179345.
W/Codec2Client(12643): query -- param skipped: index = 2415921170.
W/Codec2Client(12643): query -- param skipped: index = 1610614798.

**Comment by seel-channel** [comment]
Yes, in the video editor has a no-null safety FFMPEG version. At Flutter 2, FFMPEG get app crash when run any FFMPEG execution. I'm working in video_editor null-safety version and will solve this issue

**Comment by ajosecueto** [comment]
I'm not using null safety, the problem of the video_edit are:

1. When the file name or path has withe spaces throw export error. ( I fix editing the controller adding another character to the path for replace the whitespace and also editing FFMPEG in some point for path and replace it again and execute de correcto comand.
2. When the left trim over pass the right trim (start is greater than end).(fixing validating before execute command in controller
3. When user doesn't inrecat with the trim hen maxTrimDuration is set the command take all the video.

**Comment by seel-channel** [comment]
Try the newest version of package

**Comment by kahdichienja** [comment]
the app just stop on release

**Comment by LeGoffMael** [comment]
to avoid crash issue on android i used this fix : https://github.com/tanersener/mobile-ffmpeg/issues/616#issuecomment-740501984
