### ISSUE TITLE
Cropping with small crop area tends to break the UI 

### ISSUE THREAD

**Issue by madhav-sunil** [LeGoffMael/video_editor#143]
Notice the top portion where the crop icon is present.
After the cropping the Crop.preview() goes over the icon.

https://user-images.githubusercontent.com/43210323/225710226-ceb00d91-6f4d-45b4-ac6b-76aea0ee0f0b.mp4

Probably because the changing the aspectRatio messes up the logic? Just a guess

**Comment by LeGoffMael** [comment]
This issue is more likely caused by your UI implementation. I cannot reproduced it with the example app

**Comment by LeGoffMael** [comment]
close for inactivity, please let me know if you can reproduce it with the example app
