### ISSUE TITLE
Getting Error with video_player

### ISSUE THREAD

**Issue by sriharipreddy** [LeGoffMael/video_editor#15]
Because every version of video_editor depends on video_player ^1.0.1 and hlooks depends on video_player ^2.0.1, video_editor is forbidden.
So, because hlooks depends on video_editor ^1.0.3+1, version solving failed.

pub get failed (1; So, because hlooks depends on video_editor ^1.0.3+1, version solving failed.)

**Comment by seel-channel** [comment]
Done! Check the new release
