### ISSUE TITLE
'Pods-Runner' target has frameworks with conflicting names

### ISSUE THREAD

**Issue by craeft-io** [LeGoffMael/video_editor#152]
I get the same error but pod install doesn't solve it. The only way I get pod install to work is by removing ffmpeg_kit_flutter: ^5.1.0 from pubspec.yaml. But this is not a solution as I need this package for some other steps. 
Do you have any idea?

_Originally posted by @tmst999  in https://github.com/LeGoffMael/video_editor/issues/137#issuecomment-1568111736_

**Comment by LeGoffMael** [comment]
this is a known limitation that should be fixed by #146
