### ISSUE TITLE
cant cancel export while in progress

### ISSUE THREAD

**Issue by anasboyka** [LeGoffMael/video_editor#155]
I have a situation where i want to the export operation on background and im displaying the temporary thumbnail with loading indicator.. however i also have a cancel button where while exporting, i want to cancel the export part..  Is there any ways like throwing exception in the progress callback so that i can handle this using onError parameter or any method that i can use to cancel this export progress?

**Comment by LeGoffMael** [comment]
i should be possible using FFmpegKit once you get the sessionId, i will check into it

**Comment by anasboyka** [comment]
> i should be possible using FFmpegKit once you get the sessionId, i will check into it

Alright, for temporary solution, i just used try catch in onProgress function and throw exception if user pressed cancel. in the catch block, i set the exception string to "cancelled" and called videoEditorController.dispose() ..<= this is the only way to stop the progress.. in the onError function, i just check if it cancelled, display cancel, if not display the actual error..

**Comment by LeGoffMael** [comment]
Please check out the new 3.0.0 version, you will now have to handle the exportation with FFmpeg yourself, it will gives you all the control you need to cancel the export part
