### ISSUE TITLE
After editing a video on iOS, it cannot be played on an Android device

### ISSUE THREAD

**Issue by vedo1608** [LeGoffMael/video_editor#158]
I'm trying to trim a video on iPhone, but after uploading it to AWS, I cannot play it on my Android device. Raw iPhone videos are working normally, I'm only having issues with videos that have been edited with this package. The error that I get on Android device is this: 

```
Format exceeds selected codec's capabilities [id=1, mimeType=video/avc, codecs=avc1.6E001F, res=720x1280, fps=29.996986, c2.exynos.h264.decoder]
NoSupport [codec.profileLevel, avc1.6E001F, video/avc] [c2.exynos.h264.decoder, video/avc] [oriole, Pixel 6, Google, 33]
NoSupport [codec.profileLevel, avc1.6E001F, video/avc] [c2.android.avc.decoder, video/avc] [oriole, Pixel 6, Google, 33]
```

I tried several resolutions and I tried keeping the format in .MOV. Nothing helped. I also tried changing codec profile with `-profile:v baseline` custom instruction, but I got an error from ffmpeg that baseline profile does not support a bit depth of 10. This is the code I'm using:

```
await _controller.exportVideo(
      format: VideoExportFormat.mp4,
      preset: VideoExportPreset.ultrafast,
      customInstruction: "-crf 23 -movflags +faststart -s 720x1280",
      onProgress: (stats, value) => _exportingProgress.value = value,
      onError: (e, s) => _showErrorSnackBar("Error on export video :("),
      onCompleted: (file) async {
        _isExporting.value = false;
        if (!mounted) return;
        Navigator.of(context).pop(file);
      },
    );
```

Removing all of the custom instructions didn't help either. I'm using video_player package for playing the videos in my app.

**Comment by jpetro416** [comment]
Did you ever figure out what the issue was?

**Comment by vedo1608** [comment]
yes I did. I forgot to write here, sorry. So the solution was to add `-c:v libx265 -tag:v hvc1` to the custom instruction. This way it started working on both iOS and Android. The videos were really compressed and awesome for uploading, the quality loss wasn't even that bad.
But then we found a problem with the AWS recognition for violence, nudity etc. in videos as the recognition only works with x264 codec. So I did it like this `-c:v libx264 -crf 18 -c:a aac -movflags +faststart -vprofile main -pix_fmt yuv420p`. The quality stays nearly the same but the size of the videos gets much bigger. Hope this helps!

**Comment by jpetro416** [comment]
OKay thanks!
Here is the breakdown of the explanation of those commands from GPT:

-c:v libx264: This option specifies the video codec to be used during the encoding process. In this case, it's set to libx264, which refers to the x264 video codec. x264 is a widely used open-source software library for encoding video streams into the H.264/MPEG-4 AVC (Advanced Video Coding) format.

-crf 18: This is the Constant Rate Factor (CRF) value, which determines the video quality and compression level. A lower CRF value results in higher quality but larger file sizes, while a higher value produces lower quality but smaller file sizes. A CRF value of 18 strikes a balance between quality and size.

-c:a aac: This specifies the audio codec for encoding the audio portion of the video. Here, it's set to aac, which stands for Advanced Audio Coding. AAC is a commonly used audio codec known for its efficient compression and good audio quality.

-movflags +faststart: This flag sets a MOV (QuickTime) video file to be "fast-start" or "web optimized." Fast start is a feature that rearranges the internal structure of the video file, allowing it to begin playing before the entire file is downloaded. This is particularly useful for web streaming, as it reduces buffering times.

-vprofile main: This sets the video profile for the encoding process. Video profiles define a set of encoding parameters that are optimized for specific use cases or devices. The main profile is a common and widely supported profile that provides a good balance between compression efficiency and compatibility.

-pix_fmt yuv420p: This option specifies the pixel format of the output video. yuv420p is a widely supported pixel format that uses 4:2:0 chroma subsampling. It strikes a good balance between color accuracy and compression efficiency.

Putting it all together, the FFMPEG command you provided (-c:v libx264 -crf 18 -c:a aac -movflags +faststart -vprofile main -pix_fmt yuv420p) is used to convert and encode a video using the libx264 codec with a CRF value of 18 for video quality, AAC codec for audio, fast start for web optimization, the main video profile, and the yuv420p pixel format. This combination of options aims to produce a video file with good quality, reasonable compression, compatibility with various devices and players, and optimized for web streaming

**Comment by LeGoffMael** [comment]
Thank you for providing more information about the ffmpeg commands.
However, since the 3.0.0 version of video_editor the exportation is not handled by the package itself. It only provides a quick commands to run with ffmpeg. Please reopen an issue or a PR if you think the `VideoFFmpegVideoEditorConfig` class should be updated.
