### ISSUE TITLE
cannot crop

### ISSUE THREAD

**Issue by arashbi** [LeGoffMael/video_editor#16]
I notice that even in the example application, I cannot save and export. 
It seems the reason is that the video has a rotation - btw, this is just a video I took by phone - and the crop doesn't take that into account. 

If I switch the width and length of the crop, it works.

**Comment by Niko-by** [comment]
> I notice that even in the example application, I cannot save and export.
> It seems the reason is that the video has a rotation - btw, this is just a video I took by phone - and the crop doesn't take that into account.
> 
> If I switch the width and length of the crop, it works.

Check out this thread, I think these are related issues, I had the same one.
[https://github.com/seel-channel/video_editor/issues/20](url)

**Comment by bojidartonchev** [comment]
Hello,

I added some fixes to my local fork and now it seems working. Could you give it a try before creating a pull request?

Change **video_editor** dependencie in **pubspec.yaml** to:
```
video_editor:
    git:
      url: https://github.com/bojidartonchev/video_editor
```
