### ISSUE TITLE
Crop, Rotation not working. Showing error "_Exception Error on export video :("

### ISSUE THREAD

**Issue by jerrypaulsam** [LeGoffMael/video_editor#161]
Hello

Crop or rotation are not working and throwing an error with the exception.

`[log] FFmpeg start process with command = -ss 0:00:00.000000 -i '/data/user/0/com.example.project/cache/0bb0262f-c907-4379-a8dd-b9bd8fbf5b17/VID-20230724-WA0000.mp4' -t 0:01:29.838000 -vf 'transpose=2,transpose=2'   -y '/data/user/0/com.example.project/cache/feed-b8d403e8-6a9e-47f9-8474-8a87e4565200_1690426625486.mp4'`

`[log] FFmpeg start process with command = -i '/data/user/0/com.example.project/cache/VID-20230724-WA0000.jpg' -vf 'transpose=2,transpose=2' -y '/data/user/0/com.example.project/cache/thumb-00df04fe-304a-4f01-ad8d-bf65dafc3a42_1690426625927.jpg'`

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=qOl8bvus788

**Comment by LeGoffMael** [comment]
The logs you pasted here are no error but just information log.
