### ISSUE TITLE
Ultra HD Video isn't exporting. 

### ISSUE THREAD

**Issue by RzTutul** [LeGoffMael/video_editor#162]

**Comment by jerrypaulsam** [comment]
Did you find any solution?

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=qOl8bvus788

**Comment by RzTutul** [comment]
> Did you find any solution?

not yet

**Comment by LeGoffMael** [comment]
Hello, since the 3.0.0 version of video_editor, the exportation is not handled by the package itself. It only provides a quick commands to run with ffmpeg. Please reopen an issue or a PR if you think the `VideoFFmpegVideoEditorConfig` class should be updated.
