### ISSUE TITLE
What versions of iOS and Android does this support?

### ISSUE THREAD

**Issue by noriHanda** [LeGoffMael/video_editor#163]
Adding the info about minimum requirements for iOS/Android would be very helpful :)

I know dependencies of this project, `package:path_provider` and `package:video_player` only support iOS 11 or higher and Android SDK 16 or higher, so that should at least be the minimum requirements.

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=qOl8bvus788

**Comment by LeGoffMael** [comment]
thanks! i will add it to the readme
