### ISSUE TITLE
Preffered Aspect Ratio on crop not working properly.

### ISSUE THREAD

**Issue by bojidartonchev** [LeGoffMael/video_editor#17]
Hello.

I am trying to implement square crop. I have the following code in my `void initState()`

```
_controller
      ..initialize().then((_) {
        _controller.preferredCropAspectRatio = 1;
        _controller.updateCrop();
        _controller.video.play();
      });
```

[This is the result](https://imgur.com/mxuzydL)

If I move the crop grid, it resizes [properly](https://imgur.com/AVm3z5C):

I am using **video_editor 1.1.0**

Thanks in advance for any suggestions.

**Comment by seel-channel** [comment]
I think it doesn't work because `_controller.updateCrop()` doesn't notifyListeners. Try this and tell me if it works.

```dart
_controller.preferredCropAspectRatio = 1;
_controller.updateCrop();
_controller
    ..initialize().then((_) {
      _controller.video.play();
    });
```

**Comment by bojidartonchev** [comment]
Hello @seel-channel,

That way it doesn't work at all.
