### ISSUE TITLE
Default Trim to 30sec

### ISSUE THREAD

**Issue by xanf-code** [LeGoffMael/video_editor#2]
Hey, first of all Wonderfull package : )

How do i keep the trim default to 30 seconds?
For Example, Whatsapp Status where a video longer than 30 seconds cannot be uploaded.

Thanks : )

**Comment by seel-channel** [comment]
There is no way to put a maximum duration, but in the next update I will add it

**Comment by xanf-code** [comment]
That's nice, definitely helpful : ) !
Also what's with the drastic increase in the application size?

Before using the plugin the size of the application was around 23-24mb.

After adding the plugin the size skyrocketed to 85-90mb.

**Comment by seel-channel** [comment]
wow! I think it is by using external dependencies like the ffmpeg

**Comment by xanf-code** [comment]
That's always been a problem with packages using ffmpeg. They do provide a quick fix tho where adding : 

aaptOptions {
      ignoreAssetsPattern "!x86:!*ffprobe"
  }
  
this would cut down the size from 80-90 ish to around 50mb , which is still a lot for a 19-21mb application.

**Comment by seel-channel** [comment]
I think you can also reduce the weight by changing the ffmpeg package. For example from **full-lts** to **min-lts**

**Comment by xanf-code** [comment]
> I think you can also reduce the weight by changing the ffmpeg package. For example from **full-lts** to **min-lts**

I tried it as well, doesn't really change anything.

**Comment by Ahmed11300** [comment]
And please put in the next update to put the logo on the video

**Comment by xanf-code** [comment]
> And please put in the next update to put the logo on the video

Recommend you to open a new issue if any.

**Comment by seel-channel** [comment]
> And please put in the next update to put the logo on the video

Please open a new Issue and explain to me with more details.

**Comment by GSPrakashNaidu** [comment]
Hi, 

This plugin looks really cool...

@xanf-code, @seel-channel  we can use some part of code from [https://pub.dev/packages/video_trimmer](url) package. If this is the case even I will also work on this.

Thanks :)

**Comment by xanf-code** [comment]
> Hi, 
> 
> This plugin looks really cool...
> 
> @xanf-code, @seel-channel  we can use some part of code from [https://pub.dev/packages/video_trimmer](url) package. If this is the case even I will also work on this.
> 
> Thanks :)

Yes, exactly.

And the issue with the space has to be solved ASAP I guess. Even the most minimum version of FFMPEG is increasing the app size by >20mb :/

**Comment by seel-channel** [comment]
I added the **TrimSlider max duration argument.** If you want to set a 30seconds max duration as WhatsApp, you do this:

```dart
TrimSlider (maxDuration: Duration (seconds: 30));
```
