### ISSUE TITLE
Bug: Invalid too big or non positive size for width '640' or height '352

### ISSUE THREAD

**Issue by paricleu** [LeGoffMael/video_editor#20]
```
I/flutter (21361): [graph 0 input from stream 0:0 @ 0x7158586a00] sws_param option is deprecated and ignored
I/flutter (21361): [Parsed_crop_0 @ 0x7158586940] Invalid too big or non positive size for width '640' or height '352'
I/flutter (21361): [Parsed_crop_0 @ 0x7158586940] Failed to configure input pad on Parsed_crop_0
I/flutter (21361): Error reinitializing filters!
I/flutter (21361): Failed to inject frame into filter network: Invalid argument
I/flutter (21361): Error while processing the decoded data for stream #0:0
D/flutter-ffmpeg(21361): FFmpeg exited with rc: 1
I/flutter (21361): Conversion failed!
I/flutter (21361): ERROR ON EXPORT VIDEO (CODE 1)
```

It seems to be a problem with ffmpeg cropping(see https://superuser.com/questions/1474942/ffmpeg-cropping-invalid-too-big-or-non-positive-size-for-width)

The error is always thrown even if the user doesn't want to crop the video so the trimming does not work at all.

Probably related to #16 as another video with width 352 and height 640 does not throw the error.

**Comment by Niko-by** [comment]
> ```
> I/flutter (21361): [graph 0 input from stream 0:0 @ 0x7158586a00] sws_param option is deprecated and ignored
> I/flutter (21361): [Parsed_crop_0 @ 0x7158586940] Invalid too big or non positive size for width '640' or height '352'
> I/flutter (21361): [Parsed_crop_0 @ 0x7158586940] Failed to configure input pad on Parsed_crop_0
> I/flutter (21361): Error reinitializing filters!
> I/flutter (21361): Failed to inject frame into filter network: Invalid argument
> I/flutter (21361): Error while processing the decoded data for stream #0:0
> D/flutter-ffmpeg(21361): FFmpeg exited with rc: 1
> I/flutter (21361): Conversion failed!
> I/flutter (21361): ERROR ON EXPORT VIDEO (CODE 1)
> ```
> 
> 
> It seems to be a problem with ffmpeg cropping(see https://superuser.com/questions/1474942/ffmpeg-cropping-invalid-too-big-or-non-positive-size-for-width)
> 
> 
> The error is always thrown even if the user doesn't want to crop the video so the trimming does not work at all.
> 
> 
> Probably related to #16 as another video with width 352 and height 640 does not throw the error.

I had such a problem, I had to download the source and modify it a little. The problem is that the size of the vertical and horizontal video is not detected correctly. You need to change the function in the controller.dart file. As a result, it should look like this:

```
Future<void> _getVideoDimensions() async {
    if (!(_videoHeight > 0 && _videoWidth > 0)) {
      _videoHeight = video.value.size.height.round();
      _videoWidth = video.value.size.width.round();
    }
  }
```

This may not be the best solution, but it works. Hopefully the author will fix this problem soon.

**Comment by bojidartonchev** [comment]
Maybe the proper way of fixing this is detecting the video rotation, using the video stream's **side_data_list** property. In that list of properties there should be a rotation, which will indicate if the video has been rotated while captured. I used the following code before replacing the **ffmpeg** plugin with **video_editor**. Basically just switching the width and the height of the video if rotation is detected. Hope this helps.

```
final FlutterFFprobe _flutterFFprobe = new FlutterFFprobe();
var fileInfo = await _flutterFFprobe.getMediaInformation(file.path);

final streamsInfoArray = fileInfo.getStreams();

if (streamsInfoArray.length > 0) {
    for (var streamsInfo in streamsInfoArray) {
        if (streamsInfo.getAllProperties()['codec_type'] == 'video') {
            int width = streamsInfo.getAllProperties()['width'];
            int height = streamsInfo.getAllProperties()['height'];

            //If video is portrait mode use the rotate to adjust
            final metadataMap = streamsInfo.getAllProperties()['side_data_list'];
            if (metadataMap != null) {
                for (var metadata in metadataMap) {
                    if (metadata.containsKey('rotation')) {
                        int rotate = metadata['rotation'];
                        var rotateTimes = rotate / 90;
                        if (rotateTimes % 2 != 0) {
                            width = streamsInfo.getAllProperties()['height'];
                            height = streamsInfo.getAllProperties()['width'];
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by bojidartonchev** [comment]
Hello,

I added some fixes to my local fork and now it seems working. Could you give it a try before creating a pull request?

Change **video_editor** dependencie in **pubspec.yaml** to:
```
video_editor:
    git:
      url: https://github.com/bojidartonchev/video_editor
```
