### ISSUE TITLE
_edtorController.export() exception occurs after saving 3-4 files continuously.

### ISSUE THREAD

**Issue by Uuttssaavv** [LeGoffMael/video_editor#22]
void _exportVideo() async {
    Misc.delayed(1000, () => _isExporting.value = true);
    //NOTE: To use [-crf 17] and [VideoExportPreset] you need ["min-gpl-lts"] package
    final File file = await _controller.exportVideo(
      customInstruction: "-crf 17",
      // preset: VideoExportPreset.medium,
      format: "gif",
      progressCallback: (statics) {
        if (_controller.video != null)
          _exportingProgress.value =
              statics.time / _controller.video.value.duration.inMilliseconds;
      },
    );
    _isExporting.value = false;
    // GallerySaver.saveImage() for GIF or GallerySaver.saveVideo() for VIDEOS
    //Note: GallerySave don't override files.
    if (file != null) {
      await GallerySaver.saveVideo(file.path, albumName: "Video Editor");
      widget.recordingFunction.videoFile = file;
      await widget.recordingFunction.editingComplete(file);
      // goBack(context);
      _exportText = "Video success export!";
    } else {
      _exportText = "Error occured while saving the file";
    }
    Misc.delayed(2000, () => setState(() => _exported = false));

    setState(() => _exported = true);
  }

**Comment by LeGoffMael** [comment]
does this error still occur in latest 1.2.3 ?
