### ISSUE TITLE
FFmpeg exited with rc: 1

### ISSUE THREAD

**Issue by Usama3074** [LeGoffMael/video_editor#23]
[graph 0 input from stream 0:0 @ 0x7f8bd68fc0] sws_param option is deprecated and ignored
I/flutter ( 5621): [Parsed_crop_0 @ 0x7f8bd68f00] Invalid too big or non positive size for width '720' or height '480'
I/flutter ( 5621): [Parsed_crop_0 @ 0x7f8bd68f00] Failed to configure input pad on Parsed_crop_0
I/flutter ( 5621): Error reinitializing filters!
I/flutter ( 5621): Failed to inject frame into filter network: Invalid argument
I/flutter ( 5621): Error while processing the decoded data for stream #0:0
I/flutter ( 5621): [aac @ 0x7f74ef5500] Qavg: nan
D/flutter-ffmpeg( 5621): FFmpeg exited with rc: 1
I/flutter ( 5621): ERROR ON EXPORT VIDEO (CODE 1)
I/flutter ( 5621): Conversion failed!

**Comment by Usama3074** [comment]
i have tried every solution available but still getting this error.

**Comment by Niko-by** [comment]
> [graph 0 input from stream 0:0 @ 0x7f8bd68fc0] sws_param option is deprecated and ignored
> I/flutter ( 5621): [Parsed_crop_0 @ 0x7f8bd68f00] Invalid too big or non positive size for width '720' or height '480'
> I/flutter ( 5621): [Parsed_crop_0 @ 0x7f8bd68f00] Failed to configure input pad on Parsed_crop_0
> I/flutter ( 5621): Error reinitializing filters!
> I/flutter ( 5621): Failed to inject frame into filter network: Invalid argument
> I/flutter ( 5621): Error while processing the decoded data for stream #0:0
> I/flutter ( 5621): [aac @ 0x7f74ef5500] Qavg: nan
> D/flutter-ffmpeg( 5621): FFmpeg exited with rc: 1
> I/flutter ( 5621): ERROR ON EXPORT VIDEO (CODE 1)
> I/flutter ( 5621): Conversion failed!

Hi. It looks like the author of the plugin is in no hurry to fix bugs)) In this thread #20  I wrote a temporary solution

**Comment by bojidartonchev** [comment]
Hello,

I added some fixes to my local fork and now it seems working. Could you give it a try before creating a pull request?

Change **video_editor** dependencie in **pubspec.yaml** to:
```
video_editor:
    git:
      url: https://github.com/bojidartonchev/video_editor
```

**Comment by filizsenturk** [comment]
FFmpeg exited with rc: 1
This means ffmpeg comand has an error.. you wrote the ffmpeg command wrong.. try to check your command.. if they  are true and commands works truely then FFmpeg exited with rc: 0
