### ISSUE TITLE
Video quality when exporting

### ISSUE THREAD

**Issue by leonalonso** [LeGoffMael/video_editor#3]
Hello! 
Congratulations for the package! It is built very well. 

I only have one question, when exporting a video how do i always keep the quality?
Right now when I export the video the result is very bad.

void _exportVideo() async {
    final File file = await _controller.exportVideo(
      videoFormat: "mov",
    );
.............

Is there any way to keep the same video quality as imported from the gallery?
Thanks :)

**Comment by seel-channel** [comment]
Yo también me había percatado de ese problema, pero creo que es la manera que lo exportar el FMMPEG. Pero para la siguiente actualización voy a ver si existe una alternativa.

**Comment by leonalonso** [comment]
Fantastic! 
Thanks a lot! :)
I look forward to future updates

**Comment by seel-channel** [comment]
On release 1.0.2 I added the VideoExportPreset for change quality-compression and a custom-instruction. I didn't found a good result for loss quality, but you can use FFMPEG custom instruction.

**Comment by seel-channel** [comment]
I just solved that problem at 1.0.3 version. You **need** use "min-gpl-lts" package
