### ISSUE TITLE
Is `min-gpl-lts` needed?

### ISSUE THREAD

**Issue by shilangyu** [LeGoffMael/video_editor#38]
> Add on `android/build.gradle` file and define package name in `ext.flutterFFmpegPackage` variable.
>
> ```gradle
> ext.flutterFFmpegPackage = "min-gpl-lts"
> ```

Such a requirement means this library cannot be used in a closed source project, and as far as I know (I Am Not A Lawyer) every software using it has to be licensed under GPL as well (including this package, `video_editor`).

**Comment by seel-channel** [comment]
Really no. But It preferred use it because has the lower weight and it can use x264 and x265 libraries (.mp4). Also, it has the best compression and video quality on export
