### ISSUE TITLE
Assigning wrong values and getting error

### ISSUE THREAD

**Issue by umer322** [LeGoffMael/video_editor#4]
in your controller.dart from line check line 24 you will see the issue
 CropGridStyle trimStyle,
    TrimSliderStyle cropStyle,
  })  : assert(file != null),
        _videoController = VideoPlayerController.file(file),
        this.cropStyle = cropStyle ?? CropGridStyle(),
        this.trimStyle = trimStyle ?? TrimSliderStyle();

**Comment by seel-channel** [comment]
Can you explain me with more details the issue?

**Comment by umer322** [comment]
you are assigning cropGridStyle to trimSilderStyle 
CropGridStyle trimStyle,
TrimSliderStyle cropStyle,

**Comment by umer322** [comment]
when i set trimStyle it asks me to set trimStyle:CropGridStyle or it gives error

**Comment by seel-channel** [comment]
JAJAJJAJAJAJA

**Comment by seel-channel** [comment]
Thanks for your Issue I solved that problem on release 1.0.2 :)
