### ISSUE TITLE
app is getting crash in release mode

### ISSUE THREAD

**Issue by priyeshbhuva** [LeGoffMael/video_editor#41]
SDK: Flutter (Channel stable, 2.5.3

Im running an [example](https://github.com/seel-channel/video_editor/tree/master/example) that is provided by the repo itself. 

In debug more its working perfect without `ext.flutterFFmpegPackage  = "min-gpl-lts"` also, but in release app is getting crash with and without `ext.flutterFFmpegPackage  = "min-gpl-lts"`.

@seel-channel @LeGoffMael @paricleu @FelipeMurguia please have a look.

**Comment by priyeshbhuva** [comment]
After adding `proguard-rules.pro` it's working for me now

```
-keep class com.arthenica.mobileffmpeg.Config {
    native <methods>;
    void log(long, int, byte[]);
    void statistics(long, int, float, float, long , int, double, double);
}

-keep class com.arthenica.mobileffmpeg.AbiDetect {
    native <methods>;
}
```

**Comment by LeGoffMael** [comment]
yes, it is a flutter-ffmpeg error, here is the link to the fix : https://github.com/tanersener/mobile-ffmpeg/issues/616#issuecomment-740501984

**Comment by priyeshbhuva** [comment]
If possible add this in README file
