### ISSUE TITLE
how can I set fixed trim slider for min and max duration of length. Also trim slider can not move forward or backward

### ISSUE THREAD

**Issue by ViruRock** [LeGoffMael/video_editor#42]
how can I set fixed trim slider for min and max duration of length.
Also trim slider can not move forward or backward

**Comment by LeGoffMael** [comment]
You can check the example to set up a max duration

```dart
@override
  void initState() {
    _controller = VideoEditorController.file(widget.file,
        maxDuration: Duration(seconds: 30))
      ..initialize().then((_) => setState(() {}));
    super.initState();
  }
```

min duration is however not supported yet

**Comment by GelidGeorge** [comment]
Could you add a feature where minDuration could be set...

**Comment by GelidGeorge** [comment]
Currently I am displaying a message to trim for 15 seconds...
It would be nice if user cannot go less than 15 seconds mark or the desired mark...

**Comment by GelidGeorge** [comment]
after upgrading to flutter v3 I am getting some warnings

 Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/cover/cover_viewer.dart:114
- 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Development/flutter_sdk/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
                                WidgetsBinding.instance!

it would be helpful if you could address this ASAP

**Comment by LeGoffMael** [comment]
@GelidGeorge V1.4.2 is available with flutter 3 update to remove the warnings

I probably won't have time to work on a new feature in the next couple of weeks. But If you really need it you can submit a PR that I will be happy to review

**Comment by LeGoffMael** [comment]
`minDuration` is now supported in v2.1.0
