### ISSUE TITLE
More than 30 seconds video is not playing and Bottom Overflow Error

### ISSUE THREAD

**Issue by naveenlearner38** [LeGoffMael/video_editor#43]
Hi, 
The same example code I run in Flutter v2.5.3. Less than 30 Seconds videos are playing well but more than 30 seconds videos, playing only 1 second, repeating again and again. As well as throwing Bottom Overflow by 99945 pixels error in trim section. I attached output screenshot link below:

https://drive.google.com/file/d/1n-_iDRztDoczcz3RiY4yhA4i7o3an1EB/view?usp=sharing

**Comment by LeGoffMael** [comment]
Hi,
I just tried with a video of 2 min (vertical orientation as well) and it worked well, did you get any error in logs ?
