### ISSUE TITLE
trimslider takes too much time to generate thumbnails

### ISSUE THREAD

**Issue by umer322** [LeGoffMael/video_editor#5]
when i open a video it takes 10-15 secs to generate all thumbnails of a video

i was using this function before with videothumbnail package and it took 3-5secs mostly to get all thumbnail even in high quality

Stream<List<Uint8List>> generateThumbnails(String video) async* {
    final String _videoPath = video;
    int videoDuration=await getVideoLength(File(video));

    double _eachPart = videoDuration / 10;
    print(_eachPart);

    List<Uint8List> _byteList = [];

    for (int i = 1; i <= 10; i++) {
      print((_eachPart * i).toInt());
      Uint8List _bytes;
      _bytes = await VideoThumbnail.thumbnailData(
        video: _videoPath,
        imageFormat: ImageFormat.JPEG,
        timeMs: (_eachPart * i).toInt(),
        quality: 80,
      );
      _byteList.add(_bytes);

      yield _byteList;
    }
  }

**Comment by seel-channel** [comment]
At the beginning I had used a stream for the generation of the thumbnails but I had a problem that when I pressed the trim slider the Stream would update again

**Comment by seel-channel** [comment]
Thanks for your Issue I improved the TrimSlider on release 1.0.2 :)
