### ISSUE TITLE
i want to update Trim

### ISSUE THREAD

**Issue by akshayrupareliya0912** [LeGoffMael/video_editor#59]
i don't get any solution for updating trim any suggestion

**Comment by LeGoffMael** [comment]
You can run the [example](https://github.com/seel-channel/video_editor/tree/master/example) project, it sounds very similar to your description.

**Comment by akshayrupareliya0912** [comment]
I used this example but it is not working

**Comment by LeGoffMael** [comment]
Please be specific, what problem are you facing ?

**Comment by akshayrupareliya0912** [comment]
I can't update the trim

class _TrimScreenState extends State<TrimScreen> {
  final _exportingProgress = ValueNotifier<double>(0.0);
  final _isExporting = ValueNotifier<bool>(false);
  final double height = 60;
  VideoEditorController _controller;


  var command;
  double pos;
  double end;


  @override
  void initState() {
    _controller = VideoEditorController.file(widget.controller.file,
        maxDuration: Duration(seconds: 1000))
      ..initialize().then((_) => setState(() {}));
    };
    super.initState();
  }

  @override
  void dispose() {
    _exportingProgress.dispose();
    _isExporting.dispose();
    _controller.dispose();
    super.dispose();
  }

  String formatter(Duration duration) => [
        duration.inMinutes.remainder(60).toString().padLeft(2, '0'),
        duration.inSeconds.remainder(60).toString().padLeft(2, '0')
      ].join(":");

  List<Widget> _trimSlider() {
    return [
      AnimatedBuilder(
        animation: _controller.video,
        builder: (_, __) {
          final duration = _controller.video.value.duration.inSeconds;
          pos = _controller.trimPosition * duration;
          final start = _controller.minTrim * duration;
          end = _controller.maxTrim * duration;

          return Padding(
            padding: Margin.horizontal(height / 4),
            child: Row(children: [
              TextDesigned(formatter(Duration(seconds: pos.toInt()))),
              Expanded(child: SizedBox(width: 10)),
              TextDesigned(formatter(Duration(seconds: end.toInt()))),
              OpacityTransition(
                visible: _controller.isTrimming,
                child: Row(mainAxisSize: MainAxisSize.min, children: [
                  TextDesigned(formatter(Duration(seconds: start.toInt()))),
                  SizedBox(width: 10),
                  TextDesigned(formatter(Duration(seconds: end.toInt()))),
                ]),
              )
            ]),
          );
        },
      ),
      Container(
        width: MediaQuery.of(context).size.width,
        margin: Margin.vertical(height / 4),
        child: TrimSlider(
             // child: TrimTimeline(controller: _controller),
            controller: _controller,
            height: height,
            horizontalMargin: height / 4),
      )
    ];
  }

  // void TrimSave() async {
  //   var path = await ExtStorage.getExternalStorageDirectory();
  //   print(path);  // /storage/emulated/0
  // }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: Text("Trim"),
          centerTitle: true,
          leading: IconButton(
            icon: Icon(
              Icons.close,
              color: Colors.white,
            ),
            onPressed: () => Navigator.pop(context),
            color: Colors.black,
          ),
          actions: [
            IconButton(
                icon: Icon(Icons.done),
                onPressed: () {
                 _controller.updateTrim(pos, end);
                  context.goBack();
                })
          ],
        ),

**Comment by LeGoffMael** [comment]
once again, please be specific, explain what you are doing, the expected result and the actual result.

share the log, screenshot or video capture related to your issue.

your code itself does not help.

"I can't update the trim" does not give us enough info.

**Comment by akshayrupareliya0912** [comment]
//@dart=2.9
import 'package:ext_storage/ext_storage.dart';
import 'package:flutter/material.dart';
import 'package:helpers/helpers/extensions/build_context.dart';
import 'package:helpers/helpers/size.dart';
import 'package:helpers/helpers/transition.dart';
import 'package:helpers/helpers/widgets/text.dart';
import 'package:video_editor/domain/bloc/controller.dart';
import 'package:video_editor/ui/crop/crop_grid.dart';
import 'package:video_editor/ui/trim/trim_slider.dart';

class TrimScreen extends StatefulWidget {
  TrimScreen({Key key, this.controller}) : super(key: key);

  final VideoEditorController controller;

  @override
  _TrimScreenState createState() => _TrimScreenState();
}

class _TrimScreenState extends State<TrimScreen> {
  final _exportingProgress = ValueNotifier<double>(0.0);
  final _isExporting = ValueNotifier<bool>(false);
  final double height = 60;
  VideoEditorController _controller;

  Future<String> _getPath() {
    return ExtStorage.getExternalStoragePublicDirectory(
        ExtStorage.DIRECTORY_DOWNLOADS + "/video.mp4");
  }

  var command;
  double pos;
  double end;


  @override
  void initState() {
    _controller = VideoEditorController.file(widget.controller.file,
        maxDuration: Duration(seconds: 1000))
      ..initialize().then((_) => setState(() {}));
    super.initState();
  }

  @override
  void dispose() {
    _exportingProgress.dispose();
    _isExporting.dispose();
    _controller.dispose();
    super.dispose();
  }

  String formatter(Duration duration) => [
        duration.inMinutes.remainder(60).toString().padLeft(2, '0'),
        duration.inSeconds.remainder(60).toString().padLeft(2, '0')
      ].join(":");

  List<Widget> _trimSlider() {
    return [
      AnimatedBuilder(
        animation: _controller.video,
        builder: (_, __) {
          final duration = _controller.video.value.duration.inSeconds;
          pos = _controller.trimPosition * duration;
          final start = _controller.minTrim * duration;
          end = _controller.maxTrim * duration;

          return Padding(
            padding: Margin.horizontal(height / 4),
            child: Row(children: [
              TextDesigned(formatter(Duration(seconds: pos.toInt()))),
              Expanded(child: SizedBox(width: 10)),
              TextDesigned(formatter(Duration(seconds: end.toInt()))),
              OpacityTransition(
                visible: _controller.isTrimming,
                child: Row(mainAxisSize: MainAxisSize.min, children: [
                  TextDesigned(formatter(Duration(seconds: start.toInt()))),
                  SizedBox(width: 10),
                  TextDesigned(formatter(Duration(seconds: end.toInt()))),
                ]),
              )
            ]),
          );
        },
      ),
      Container(
        width: MediaQuery.of(context).size.width,
        margin: Margin.vertical(height / 4),
        child: TrimSlider(
             // child: TrimTimeline(controller: _controller),
            controller: _controller,
            height: height,
            horizontalMargin: height / 4),
      )
    ];
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.black,
          title: Text("Trim"),
          centerTitle: true,
          leading: IconButton(
            icon: Icon(
              Icons.close,
              color: Colors.white,
            ),
            onPressed: () => Navigator.pop(context),
            color: Colors.black,
          ),
          actions: [
            IconButton(
                icon: Icon(Icons.done),
                onPressed: () {
                  _controller.updateTrim(pos, end);
                 
                  context.goBack();
                })
          ],
        ),
        backgroundColor: Colors.black,
        body: Center(
        
          child: SingleChildScrollView(
            child: Column(
              children: [
                Container(
                  height: 484,
                  width: 272,
                  color: Colors.white,
                  child: Column(
                    children: [
                      Stack(alignment: Alignment.center, children: [
                        Center(
                            child: CropGridViewer(
                          controller: _controller,
                          showGrid: false,
                        )),
                        AnimatedBuilder(
                          animation: _controller.video,
                          builder: (_, __) => OpacityTransition(
                            visible: !_controller.isPlaying,
                            child: GestureDetector(
                              onTap: _controller.video.play,
                              child: Container(
                                width: 40,
                                height: 40,
                                decoration: BoxDecoration(
                                  color: Colors.white,
                                  shape: BoxShape.circle,
                                ),
                                child:
                                    Icon(Icons.play_arrow, color: Colors.black),
                              ),
                            ),
                          ),
                        ),
                      ]),
                    ],
                  ),
                ),
                Container(
                  child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: _trimSlider()),
                ),
              ],
            ),
          ),
        ));
  }
}

**Comment by LeGoffMael** [comment]
man, please read what i wrote above, i won't answer anymore unless you provide proper explanations (log error, screenshot, detailed explanation). `Not a copy/paste of your code`.

**Comment by akshayrupareliya0912** [comment]
sorry  I have recently started this so i can't know how to do

**Comment by akshayrupareliya0912** [comment]
I want to update trim by using video editor package?

**Comment by akshayrupareliya0912** [comment]
☺☻

**Comment by akshayrupareliya0912** [comment]
☺
