### ISSUE TITLE
The getter 'value' was called on null.

### ISSUE THREAD

**Issue by xanf-code** [LeGoffMael/video_editor#6]
Haven't done anything but i'm facing this issue after copy pasting the code from the provided example file.

![Screenshot_20210114-204938](https://user-images.githubusercontent.com/65482184/104611752-7955e200-56ab-11eb-9cf5-b962744ba114.jpg)

**Comment by seel-channel** [comment]
😭

**Comment by xanf-code** [comment]
@seel-channel any idea what's causing the issue tho?

**Comment by seel-channel** [comment]
Yes, it is. I just solved that. I going to tell you when I upload the new release

**Comment by seel-channel** [comment]
Done! On release 1.0.2 I solved that problem and improved the cropping gestures

**Comment by xanf-code** [comment]
@seel-channel that was quick one, thanks mate 👍🚀

**Comment by xanf-code** [comment]
Update: Unable to use "min-lts" , throwing preset related errors.

Using "full-lts" will boost the app size to 80-100mb.

Rest all is working as expected 👍

**Comment by seel-channel** [comment]
OMG! I will remove VideoExportPreset and you can use customInstruction to manually add a preset

**Comment by xanf-code** [comment]
To be more precise.

customInstruction: "-crf 17",
preset: VideoExportPreset.veryslow,

Using the above with "min-lts" throws out two error, one regarding the preset that I've mentioned above and the other one with the custom instruction as well. Something like "crf-17" cannot be found. 👍
