### ISSUE TITLE
Video size with more than 50+mb does not get trim 

### ISSUE THREAD

**Issue by swapnilsinha17** [LeGoffMael/video_editor#61]
I am trying to implement crop and trim function but on extract cover and video it gives me error 

"Error on cover exportation";

**Comment by LeGoffMael** [comment]
What is the error message in the log ?

**Comment by aditya-mahajan96** [comment]
> What is the error message in the log ?

I am using ffmpeg_kit_flutter: ^4.5.0 for my video merge and for video trim your plugin video_editor: ^1.2.2. When my video size is big   its giving me error text that we are printing ""Error on cover exportation"; as might be its not able to find the file.

**Comment by LeGoffMael** [comment]
can you check the log again using the latest updates

**Comment by LeGoffMael** [comment]
close for inactivity
