### ISSUE TITLE
Issue with trimming videos

### ISSUE THREAD

**Issue by aditya-mahajan96** [LeGoffMael/video_editor#62]
I am using ffmpeg_kit_flutter: ^4.5.0 for my video merge and for video trim your plugin video_editor: ^1.2.2. When my video size is big its giving me error text that we are printing ""Error on cover exportation"; as might be its not able to find the file.

**Comment by LeGoffMael** [comment]
Please provide the actual ffmpeg error that you should have in the log

**Comment by aditya-mahajan96** [comment]
> Please provide the actual ffmpeg error that you should have in the log

Like this i am passing my file 

 File pickedGallaryFile = File(result.files.single.path!);
              Navigator.of(context).push(
                MaterialPageRoute(builder: (context) {
                  return VideoEditor(file: File(pickedGallaryFile.path));
                }),
              );
<img width="1168" alt="Screenshot 2021-12-21 at 11 08 10 PM" src="https://user-images.githubusercontent.com/84502466/146974305-090ac31d-26de-4f2d-b387-604f646ee789.png">
 Is the error 

and code uploaded on https://justpaste.it/video_code



              and pubspec.yaml

camera: ^0.8.1+5
  video_compress: ^3.1.0
  file_picker: ^4.2.7
  video_thumbnail: ^0.4.3
  ffmpeg_kit_flutter: ^4.5.0
  gallery_saver: ^2.3.2
  simple_gesture_detector: ^0.2.0
  flutter_video_info: ^1.2.0
  video_editor: ^1.2.2
  helpers: ^1.1.1
  video_player: ^2.2.6

**Comment by LeGoffMael** [comment]
can you check the log again using the latest updates

**Comment by aditya-mahajan96** [comment]
> can you check the log again using the latest updates

How can we print log can you please tell me. Here is my code  as mentioned above too - https://justpaste.it/video_code as there isn't any such command written FFmpegKitConfig.

**Comment by aditya-mahajan96** [comment]
> can you check the log again using the latest updates

How can we print log can you please tell me. Here is my code  as mentioned above too - https://justpaste.it/video_code as there isn't any such command written FFmpegKitConfig.

**Comment by LeGoffMael** [comment]
just replace the video_editor dependency in the pubspec.yaml to use the latest update

replace
```yaml
video_editor: ^1.2.2
```
by
```yaml
video_editor:
    git:
      url: git://github.com/seel-channel/video_editor.git
```

you should now see in the log the return status, code and error message if it failed

**Comment by aditya-mahajan96** [comment]
> just replace the video_editor dependency in the pubspec.yaml to use the latest update
> 
> replace
> 
> ```yaml
> video_editor: ^1.2.2
> ```
> 
> by
> 
> ```yaml
> video_editor:
>     git:
>       url: git://github.com/seel-channel/video_editor.git
> ```
> 
> you should now see in the log the return status, code and error message if it failed

I have tried that too and for printing " ffmpeg return state and fail stack trace if exists #63" it requires command and in video_Editor there isn't any command mentioned.

**Comment by LeGoffMael** [comment]
you don't need any command, just run `exportVideo` or `extractCover` and you should now be able to see the reason why it does not work

**Comment by aditya-mahajan96** [comment]
For making the project run first i had to change my earlier plugin  of ffmpegkit also 

From 

```
ffmpeg_kit_flutter: ^4.5.0
video_editor: ^1.2.2
```


```
 ffmpeg_kit_flutter:
    git:
      url: https://github.com/shilangyu/ffmpeg-kit
      ref: development-flutter
      path: prebuilt/bundle-flutter-lts/default
  video_editor:
    git:
      url: git://github.com/seel-channel/video_editor.git
```

as using ffmpegkit with version it was giving error - 
Because every version of video_editor from git depends on ffmpeg_kit_flutter from git and **ProjectName** depends on ffmpeg_kit_flutter from hosted, video_editor from git is forbidden.
So, because **ProjectName** depends on video_editor from git, version solving failed.
pub get failed (1; So, because **ProjectName** depends on video_editor from git, version solving failed.)

and video editor as you have mentioned and when coming to state its giving error - ` FFmpeg process exited with state COMPLETED and return code 1.`
-----------------------------------------------------------------------------------------------------------------------------
**Below first image is showing what it displays when i load mp4 type video**
<img width="1160" alt="Screenshot 2021-12-26 at 12 41 11 PM" src="https://user-images.githubusercontent.com/84502466/147401600-dcb31663-eb25-4dd6-8b30-62fd01ad95f5.png">

**Second image shows the ffmpegkit status**

<img width="1198" alt="Screenshot 2021-12-26 at 12 42 22 PM" src="https://user-images.githubusercontent.com/84502466/147401608-ec071746-7e67-42d3-b2b0-bff10e82bcbb.png">

**Comment by akshayrupareliya0912** [comment]
I want to update trim by using video editor package?

**Comment by LeGoffMael** [comment]
can you please try again with the latest 1.2.3
