### ISSUE TITLE
applying rotation and then export causes corrupted video.

### ISSUE THREAD

**Issue by abhay-s-rawat** [LeGoffMael/video_editor#64]
applying rotation and then export causes corrupted video.
some logs:
NoSupport [sizeAndRate.support, 720x1280x23.975902557373047] [OMX.google.mpeg4.decoder, video/mp4v-es] [generic_x86_arm, AOSP on IA Emulator, Google, 28]

**Comment by LeGoffMael** [comment]
Are you using it on an simulator ? if so please try from a physical device

**Comment by abhay-s-rawat** [comment]
Yes it gives some errorneous video in simulator. works fine in physical device. Thanks
