### ISSUE TITLE
crop video and show in different page?

### ISSUE THREAD

**Issue by akshayrupareliya0912** [LeGoffMael/video_editor#66]
![image](https://user-images.githubusercontent.com/82557383/148490945-28003711-4433-43a2-be53-0fe99cdc5384.png)

**Comment by LeGoffMael** [comment]
Please open an issue if you found an issue with the package. If you have a problem of flutter you should try to use [Stackoverflow](https://stackoverflow.com/).

Have a look at the [example](https://github.com/seel-channel/video_editor/tree/master/example). It might help you to understand how to implement you own usage of this package.

**Comment by akshayrupareliya0912** [comment]
yes but for update trim, there is not much specific detail are there, therefore many issue is related to trim
