### ISSUE TITLE
Update crop and preview in new screen

### ISSUE THREAD

**Issue by akshayrupareliya0912** [LeGoffMael/video_editor#67]
![send on new screen ](https://user-images.githubusercontent.com/82557383/148725762-28394910-5951-453a-b3e8-434d3a30c5b5.PNG)
![crop](https://user-images.githubusercontent.com/82557383/148725763-0e362b95-19f1-4fcb-9b8e-2af2a2c4d4ba.PNG)

**Comment by seel-channel** [comment]
I don't know what is PreviewCropScreen. Send more details about it

**Comment by akshayrupareliya0912** [comment]
PreviewCropScreen is new page in which i have to show

**Comment by seel-channel** [comment]
Send me more details. I can't understand the problem

**Comment by akshayrupareliya0912** [comment]
I want to show updated crop and show on next screen

**Comment by seel-channel** [comment]
You can use the CropScreen at the [example](https://github.com/seel-channel/video_editor/blob/master/example/lib/main.dart)
