### ISSUE TITLE
After trim cover is not updating.(implemented new whatsapp like feature and look)

### ISSUE THREAD

**Issue by abhay-s-rawat** [LeGoffMael/video_editor#69]
I fixed this issue in my forked branch and I gave a whatsapp like look to the video crop bar. Please have a look at it. I did not found a way to reach you but I think it will be a value addition to this project. Plus I added a feature to apply max file size regardless of duration like whatsapp . I did this by reading file metadata audio and video bitrates. Below is the link to my repo.

https://github.com/abhay-s-rawat/video_editor

**Comment by seel-channel** [comment]
Thanks bro! We are going to take a look at it and find a way to implement it to this project uwu

**Comment by abhay-s-rawat** [comment]
No problem, you can also give a choice like either maxfile size or duration can limit the video.
I shaped my fork according to my needs , do not merge as I removed some of the things and parameters.
