### ISSUE TITLE
Error on export video :( on IOS

### ISSUE THREAD

**Issue by AyazKhalid70** [LeGoffMael/video_editor#7]
whenever i export the video the returned file is null and goes to else case showing this error

`final File file = await _controller.exportVideo(
      videoFormat: "mp4",
      customInstruction: "-crf 17", //visually lossless
      preset: VideoExportPreset.medium,
    );
    if (file != null) {
      NavigationService().goBack(file);
      _exportText = "Video success export!";
    } else {
      _exportText = "Error on export video :(";
    }`

**Comment by AyazKhalid70** [comment]
getting ERROR ON EXPORT VIDEO (CODE 1) on video_editor: ^1.0.2

**Comment by seel-channel** [comment]
Oh no! I don't have Mac to test the API. You can view the Flutter_FFMPEG documentation for iOS

**Comment by seel-channel** [comment]
I just released the 1.0.3 version. Please use it with the "min-gpl-lts" package and try it
