### ISSUE TITLE
CocoaPods could not find compatible versions for pod "ffmpeg_kit_flutter_min_gpl/min-gpl-lts

### ISSUE THREAD

**Issue by ghost** [LeGoffMael/video_editor#70]
Receiving this error on Pod Install

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: all_pods_versions_d_d_6.txt exists! Returning local because checking is only performed in repo update
      CDN: trunk Relative path: Specs/d/d/6/ReachabilitySwift/5.0.0/ReachabilitySwift.podspec.json exists! Returning local because checking is only performed
      in repo update
    [!] CocoaPods could not find compatible versions for pod "ffmpeg_kit_flutter_min_gpl/min-gpl-lts":
      In Podfile:
        ffmpeg_kit_flutter_min_gpl (from `Flutter/ephemeral/.symlinks/plugins/ffmpeg_kit_flutter_min_gpl/macos`) was resolved to 4.5.1.LTS, which depends on
          ffmpeg_kit_flutter_min_gpl/min-gpl-lts (= 4.5.1.LTS)

    Specs satisfying the `ffmpeg_kit_flutter_min_gpl/min-gpl-lts (= 4.5.1.LTS)` dependency were found, but they required a higher minimum deployment target.

**Comment by LeGoffMael** [comment]
You need to setup iOS Minimum Deployment Target to 10 in your `Podfile`.

```
platform :ios, '10.0'
```

More info about [ffmpeg_kit configuration](https://github.com/tanersener/ffmpeg-kit/tree/main/flutter/flutter)
