### ISSUE TITLE
converted callbacks to future and added functionality to limit video by duration or size

### ISSUE THREAD

**Issue by abhay-s-rawat** [LeGoffMael/video_editor#71]
Hi ,
I enhanced this a bit and added a functionality to limit video by filesize or maxduration and added methods to give a option to call export and cover functions as futures .
I did not found a way to communicate to you so I raised a issue here, please do comment your reviews and I will close this issue.

https://github.com/abhay-s-rawat/video_editor

**Comment by LeGoffMael** [comment]
Hi,
Thank you for your interest to video_editor.
Please submit your suggested modifications by making a pull request. This way we will be able to review it.

**Comment by abhay-s-rawat** [comment]
Actually I am adding one more functionality to add text to video . Like
displaying text while playing video and that text will be displayed
according to the timeline.

**Comment by LeGoffMael** [comment]
That's sounds great ! You can make a PR so we can review and apply your changes.
