### ISSUE TITLE
FFMPEG is conflicting with this package..

### ISSUE THREAD

**Issue by choiNTSBG** [LeGoffMael/video_editor#72]
I think I understand that this package has some FFMPEG dependency in it, that's why its conflicting when I pub get any FFMPEG kits. is there a way to use the FFMPEG of the video_editor? or is there a way to install both video_editor package and any ffmpeg kit's without conflicting?

**Comment by choiNTSBG** [comment]
nevermind, just found out we can use the ffmpeg_kit_flutter_min_gpl which I had to find by looking at the video_editor dependency.

**Comment by rahulvyas** [comment]
I'm also having same issue how do I resolve?
