### ISSUE TITLE
Because every version of flutter_localizations from sdk depends on path 1.8.0 and video_editor >=1.2.4

### ISSUE THREAD

**Issue by aliaktas-tr** [LeGoffMael/video_editor#79]
Because every version of flutter_localizations from sdk depends on path 1.8.0 and video_editor >=1.2.4 depends on path ^1.8.1, flutter_localizations from sdk is incompatible with video_editor >=1.2.4.
So, because sociple depends on both video_editor ^1.2.4 and flutter_localizations from sdk, version solving failed.

**Comment by LeGoffMael** [comment]
This dependency as been removed in 8ed391955c8f67bff2f672da552def6f0bcd57f3.
You can use the github master or `v1.2.3`. This fix will be included in next release.

**Comment by LeGoffMael** [comment]
new 1.2.5 is released including this fix, please let me know if you found any issue
