### ISSUE TITLE
Release with fixed path dependency and ffmpeg_kit_flutter_min_gpl LTS bug

### ISSUE THREAD

**Issue by adigladi** [LeGoffMael/video_editor#80]
Hi, writing my first issue here and I'm up for contributing if needed!

I noticed there was a fix for removing the `path` dependency some days ago, it would be super to get a release that includes this since it's currently hindering my project from upgrading due to `flutter_test from sdk depends on path 1.8.0 and video_editor >=1.2.4 depends on path ^1.8.1`.

Also we've experienced an issue with deploying to AppStore with fastlane, where it complains about the format of the `ffmpeg_kit_flutter_min_gpl` dependency:

```
This bundle is invalid.
The value for key CFBundleShortVersionString '4.5.1.LTS' in the Info.plist file at '${bundlePath}'
must be a period-separated list of at most three non-negative integers.
```

Removing the -LTS part from the dependency should solve it, if possible.

**Comment by adigladi** [comment]
As an add-on to this, the `pubspec.lock` should probably be removed since this is a library package, [see more info here](https://dart.dev/tools/pub/glossary#library-package).

**Comment by adigladi** [comment]
As an add on to this, the pubspec.lock file should probably be removed since this is a library package, [see more info here](https://dart.dev/tools/pub/glossary#library-package).

**Comment by LeGoffMael** [comment]
Hi~
You’re absolutely right I will try to upload a new version today with the fix to path library.

regarding your second point, I also faced this issue, please look at this link : https://github.com/tanersener/ffmpeg-kit/issues/323#issue-1105338811

I would recommend you to upgrade your Xcode version to 13+

**Comment by adigladi** [comment]
Thanks!

Hmm okay, I can't seem to deploy using latest xcode, wrote a comment in that ticket as well.

**Comment by adigladi** [comment]
Any reason to not upgrade to the stable version in this project? It would solve this as far as I've understood?

**Comment by LeGoffMael** [comment]
Hum as far as I remember the LTS package is necessary for some features such as preset…
I will double check

**Comment by LeGoffMael** [comment]
new version 1.2.5 is released including the `path` fix and your cleaning recommendation! Please let me know if you found an issue regarding this

I will look into the LTS package more in details

**Comment by adigladi** [comment]
Awesome! However I don't think the explicit ^1.8.0 now set is needed, I think removing the path dependency as it was done before is enough, that part was just not released yet. But upgrading to v1.2.5 is working for us now 👍  I'll look into the workarounds for the LTS-issue for us, but would be great if it's possible to upgrade here to stable.

**Comment by adigladi** [comment]
Side note, tried overriding `ffmpeg_kit_flutter_min_gpl` to use the stable version, seems to work so far for our use case!

**Comment by LeGoffMael** [comment]
The `path` package is used by exportation functions, so i don't think that it should be removed.

The `LTS` ffmpeg package is a stable version, only it supports more devices 👉 [see more about LTS release](https://github.com/tanersener/ffmpeg-kit/wiki/LTS-Releases).

Switching to the main release means that less devices / OS versions will be supported by ffmpeg. After looking into it, it does not affect the features of this package, so it would be indeed good to switch to the main release as it is probably the most used.

And like you said, people who really needs the LTS release could still override the dependency directly in their project.

**Comment by LeGoffMael** [comment]
Closed with #81

**Comment by adigladi** [comment]
Will there be a release including this soon @LeGoffMael?

**Comment by LeGoffMael** [comment]
I will try to release a new one this weekend
