### ISSUE TITLE
Trim timeline image has bug (timeline not showing images on every video select)

### ISSUE THREAD

**Issue by hasnainelahi** [LeGoffMael/video_editor#82]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/44682591/160787934-54de30d6-5ea9-4dd4-9915-024c196d40fc.png">

File: video_thumbnail.dart
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/44682591/160787998-c48c4f95-aae5-473b-b3ec-78ffeabcda52.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/44682591/160799065-3d9061cf-3db3-484d-bbdd-6a350505a2ad.png">

after that timeline does not show images

**Comment by LeGoffMael** [comment]
Hi~
Thank you for the report. If i understand well you cannot generate any thumbnails from any video selected ?

Looking at your screenshots it seems to be an error related to [video_thumbnail package](https://github.com/justsoft/video_thumbnail). It might be worth taking a look there.

Are you facing this error using video_editor previous version (before `1.2.5`) as well ?

**Comment by hasnainelahi** [comment]
It is generating thumbnails correctly, timeline images not showing...
Yes, I also tried the previous version (before 1.2.5) as well.


at the last frame: E[/MediaMetadataRetrieverJNI]()(25699): getFrameAtTime: videoFrame is a NULL pointer
Screenshot:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/44682591/160980882-884f70f4-31b6-4dbc-bfe2-96319a79652b.png">

**Comment by hasnainelahi** [comment]
Any Solution ?

**Comment by LeGoffMael** [comment]
Yes this is what i meant by thumbnail. The component that you are seeing above is just the video player.

We are using another package to generate them -> [video_thumbnail package](https://github.com/justsoft/video_thumbnail). The error is related to this library, so i can recommend you to try the example of this lib and if the error still occurs to open an issue there.

**Comment by hasnainelahi** [comment]
I am already using example. Not working ...

**Comment by LeGoffMael** [comment]
I meant the example of the [video_thumbnail package](https://github.com/justsoft/video_thumbnail).

**Comment by hasnainelahi** [comment]
this example of the video_thumbnail package
<https://github.com/justsoft/video_thumbnail> is working fine separately.
Kindly guide me please to solve this issue. I have to deliver the app.
today.
Thank you Very much bro

**Comment by LeGoffMael** [comment]
Unfortunately i am not able to reproduce your issue.
Do you have this error only with a single file or all of them ?

Would you be able to provide the file which throw the error ?

**Comment by hasnainelahi** [comment]
Getting error on single file.
I have attached the screenshot so you can see the error and also file path


1) Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.5.0/lib/video_thumbnail.dart.  Line 74

function code: 
  static Future<Uint8List?> thumbnailData({
    required String video,
    Map<String, String>? headers,
    ImageFormat imageFormat = ImageFormat.PNG,
    int maxHeight = 0,
    int maxWidth = 0,
    int timeMs = 0,
    int quality = 10,
  }) async {
    assert(video.isNotEmpty);
    final reqMap = <String, dynamic>{
      'video': video,
      'headers': headers,
      'format': imageFormat.index,
      'maxh': maxHeight,
      'maxw': maxWidth,
      'timeMs': timeMs,
      'quality': quality,
    };
    return await _channel.invokeMethod('data', reqMap); -------- error here (await)
  }



2) Developer/flutter/.pub-cache/hosted/pub.dartlang.org/video_editor-1.2.5/lib/ui/trim/thumbnail_slider.dart Line 78

function code: 
  Stream<List<Uint8List>> _generateThumbnails() async* {
    final String path = widget.controller.file.path;
    final int duration = widget.controller.video.value.duration.inMilliseconds;
    final double eachPart = duration / _thumbnails;
    List<Uint8List> _byteList = [];
    for (int i = 1; i <= _thumbnails; i++) {
      Uint8List? _bytes = await VideoThumbnail.thumbnailData( -------- error here (await)
        imageFormat: ImageFormat.JPEG,
        video: path,
        timeMs: (eachPart * i).toInt(),
        quality: widget.quality,
      );
      if (_bytes != null) {
        _byteList.add(_bytes);
      }

      yield _byteList;
    }
  }

**Comment by LeGoffMael** [comment]
I meant do you have this error with every videos or all of them?

It would be good to have more details about the video file you're getting an error with

**Comment by LeGoffMael** [comment]
I've open a similar issue on video_thumbnail package : https://github.com/justsoft/video_thumbnail/issues/106

Please checkout the 1.4.1 release.
