### ISSUE TITLE
Short Question: app got fat in size 70-80 mb

### ISSUE THREAD

**Issue by Ansh-Rathod** [LeGoffMael/video_editor#92]
hi, I have used the flutter FFmpeg plugin many times and I think the size of the app is the primary concern when you release the app.
and I'm targeting 21 API versions of android devices so I'm using FFmpeg - LTS , is there any way to reduce app size ? please if you know how to overcome this issue let me know.

**Comment by LeGoffMael** [comment]
This question belongs to the [ffmpeg_kit](https://github.com/tanersener/ffmpeg-kit) library, `video_editor` package focus on the UI to set the edition parameters.

FFmpeg repository's wiki contains 2 sections explaining this issue: [Building](https://github.com/tanersener/ffmpeg-kit/wiki/Building) and [How to Decrease Binary Size](https://github.com/tanersener/ffmpeg-kit/wiki/How-to-Decrease-Binary-Size).
