### ISSUE TITLE
Change backgroundcolor of CoverViewer

### ISSUE THREAD

**Issue by userdontknow** [LeGoffMael/video_editor#93]
Hello unfortunately theres a problem when changing color of background in black to white. We cannot change the color of the background from CoverViewer. When we change the size of the video for example, the background is always black .

**Comment by LeGoffMael** [comment]
You can use `CropGridStyle`, `TrimSliderStyle` and `CoverSelectionStyle` to change the design to your need.

Looking at what you need you could use `CropGridStyle`, `croppingBackground` and `background` param

```dart
_editorController = VideoEditorController.file
  video,
  cropStyle: CropGridStyle(background: Colors.white),
);
```

**Comment by userdontknow** [comment]
Great Thanks a lot !:)

**Comment by userdontknow** [comment]
Great Thanks a lot !:)
