### ISSUE TITLE
How to export video to custom path?

### ISSUE THREAD

**Issue by aipxperts-developer** [LeGoffMael/video_editor#95]
Hi First of all i really want to appreciate this. Currently the when i am trying to save the video, it is saving in data/app/data/com.example.example/cache/

<img width="1062" alt="Screenshot 2022-06-07 at 6 26 31 PM" src="https://user-images.githubusercontent.com/51985803/172385806-891cec0a-dae9-4336-bfe5-de9752d75322.png">

How can save it to custom path Internal Storage/Documents/App Name/Videos

**Comment by LeGoffMael** [comment]
You can use _outDir_ and _name_ parameters in _exportVideo_ function
