### ISSUE TITLE
having this error using pod install

### ISSUE THREAD

**Issue by wanoghoco** [LeGoffMael/video_editor#99]
[!] CocoaPods could not find compatible versions for pod "ffmpeg_kit_flutter_min_gpl/min-gpl":
  In Podfile:
    ffmpeg_kit_flutter_min_gpl (from `.symlinks/plugins/ffmpeg_kit_flutter_min_gpl/ios`) was resolved to 4.5.1, which depends on
      ffmpeg_kit_flutter_min_gpl/min-gpl (= 4.5.1)

Specs satisfying the `ffmpeg_kit_flutter_min_gpl/min-gpl (= 4.5.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by LeGoffMael** [comment]
Hi, you might need to increase your minimum deployment target has specified in the readme.

In your Podfile :
```
platform :ios, '12.1'
```
